import SwiftUI

// 自由组 / Quick Workout — 2 步流程, 跟 web 端 /quick/* 路由对齐
//
// Step 1 (QuickMuscleStep):  选肌群 (chip + BodyHint 实时反馈)
// Step 2 (QuickExerciseStep): 每个肌群下挑 1+ 个动作 (按匹配度排序, 可多选)
// 完成: synthesize 一个 autoGenerated Plan → 调起 PlanPlayer
//
// 跟 web 的差别 (有意简化):
//   - 不做 step 3 的"逐个动作 + 实时记录"独立 UI, 直接复用 PlanPlayer (PR + history 都走标准路径)
//   - 肌群选择用 chip + display-only BodyHint, 不实现 SVG tap-to-select 拖拽 (复杂度高, chip 体验已足够)
struct QuickWorkoutScreen: View {
    @Environment(DataStore.self) private var data
    @Environment(\.dismiss) private var dismiss
    let onStart: (Plan) -> Void

    // 整个 sheet 共享的状态
    @State private var step: Int = 1
    @State private var selectedMuscles: Set<MuscleGroup> = []
    @State private var pickedExerciseIds: Set<String> = []
    /// AI 返回的"推荐顺序" — synthesizePlan 用它决定 playlist 顺序.
    /// nil = 用户手动挑 / AI 没跑 → 走默认 category 排序.
    @State private var aiOrder: [String]? = nil

    var body: some View {
        VStack(spacing: 0) {
            header
            progressBar
            Group {
                if step == 1 {
                    QuickMuscleStep(
                        selected: $selectedMuscles,
                        onNext: { withAnimation(.easeOut(duration: 0.25)) { step = 2 } }
                    )
                } else {
                    QuickExerciseStep(
                        selectedMuscles: selectedMuscles,
                        pickedIds: $pickedExerciseIds,
                        aiOrder: $aiOrder,
                        exById: data.exById,
                        allExercises: data.exercises,
                        onStart: handleStart
                    )
                }
            }
            .transition(.opacity)
        }
        .background(MasoColor.background.ignoresSafeArea())
    }

    // MARK: - header

    private var header: some View {
        HStack(spacing: 12) {
            // 关闭 / 返回 — step 2 时变 < 返回到 step 1
            Button(action: {
                if step == 1 { dismiss() }
                else { withAnimation(.easeOut(duration: 0.25)) { step = 1 } }
            }) {
                // step 1 → xmark (关闭 sheet); step 2 → chevron.left (返回上一步),
                // 跟 iOS 标准 nav bar 返回按钮一致.
                Image(systemName: step == 1 ? "xmark" : "chevron.left")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(MasoColor.text)
                    .frame(width: 30, height: 30)
                    .background(MasoColor.surfaceHi)
                    .clipShape(Circle())
            }
            .buttonStyle(.plain)
            .accessibilityLabel(step == 1 ? "Close" : "Back")

            Spacer()
            VStack(spacing: 2) {
                Text("STEP \(step) / 2")
                    .font(.system(size: 9, weight: .heavy))
                    .tracking(2)
                    .foregroundStyle(MasoColor.accent)
                Text(step == 1 ? "Pick muscles" : "Pick exercises")
                    .font(.system(size: 14, weight: .bold))
                    .foregroundStyle(MasoColor.text)
            }
            Spacer()
            // 占位 — 让标题居中
            Color.clear.frame(width: 30, height: 30)
        }
        .padding(.top, 12)
        .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
    }

    /// 顶部进度条 — 2 段, 当前 step 高亮 accent
    private var progressBar: some View {
        HStack(spacing: 4) {
            Capsule()
                .fill(MasoColor.accent)
                .frame(height: 3)
            Capsule()
                .fill(step >= 2 ? MasoColor.accent : MasoColor.surfaceHi)
                .frame(height: 3)
        }
        .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
        .padding(.top, 12)
        .padding(.bottom, 8)
    }

    // MARK: - finish

    private func handleStart() {
        let plan = synthesizePlan()
        guard !plan.steps.isEmpty else { return }
        // 不再立即 data.updatePlan — 等用户训练完成后 CompletedView 给"Save as plan"选项,
        // 用户主动保存才入库. 自由训练的 plan 用 plan.autoGenerated == true 标识.
        // SetRecord.planId 仍指向这个 plan.id, 不入库时 History 显示"Free workout" fallback.
        onStart(plan)
        dismiss()
    }

    /// 从用户挑的 exercise IDs → 合成 Plan
    private func synthesizePlan() -> Plan {
        let picked: [Exercise] = pickedExerciseIds.compactMap { data.exById[$0] }

        // 排序逻辑:
        // 1. 如果有 AI order — 按 AI 给的顺序排, 没在 AI list 里的 (用户手动加的) 按 category fallback
        // 2. 没有 AI order — 默认 category 排序 (strength → cardio → flexibility)
        let sorted: [Exercise]
        if let aiOrder = aiOrder, !aiOrder.isEmpty {
            // 把 AI 顺序转成 lookup map (id → position)
            let positions = Dictionary(uniqueKeysWithValues: aiOrder.enumerated().map { ($1, $0) })
            // 在 AI list 里的优先, 按 AI position 排; 不在的丢后面按 category
            let inAI = picked.filter { positions[$0.id] != nil }
                .sorted { positions[$0.id]! < positions[$1.id]! }
            let extras = picked.filter { positions[$0.id] == nil }
                .sorted { l, r in
                    if l.category != r.category {
                        return l.category == .strength
                            || (l.category == .cardio && r.category == .flexibility)
                    }
                    return false
                }
            sorted = inAI + extras
        } else {
            sorted = picked.sorted { lhs, rhs in
                if lhs.category != rhs.category {
                    return lhs.category == .strength
                        || (lhs.category == .cardio && rhs.category == .flexibility)
                }
                return false
            }
        }
        let now = Date()
        let steps: [PlanStep] = sorted.enumerated().map { (i, ex) in
            // 用上次该动作的记录回填重量 / 次数 (跟 web 端 lastSetOf 一致, 这里简化为查 sets)
            let lastSet = data.sets.first(where: { $0.exerciseId == ex.id })
            let isStrength = ex.category == .strength
            return PlanStep(
                id: "qw-step-\(now.timeIntervalSince1970.rounded())-\(i)",
                exerciseId: ex.id,
                sets: 3,
                reps: isStrength ? (lastSet?.reps ?? 10) : nil,
                weight: isStrength ? (lastSet?.weight ?? 0) : nil,
                duration: isStrength ? nil : 30,
                restBetweenSets: data.settings.defaultRestSeconds,
                rest: 0
            )
        }
        let dateStr = now.formatted(.dateTime.month().day().hour().minute())
        // Plan name 走 i18n — zh-Hans "自由训练 · 5/17 9:30" / en "Free workout · 5/17 9:30"
        // 之前 hardcode "Quick · ..." 导致中文用户看英文 "Quick" 不一致.
        return Plan(
            id: "qw-\(Int(now.timeIntervalSince1970))",
            name: "\(NSLocalizedString("Free workout", comment: "")) · \(dateStr)",
            steps: steps,
            createdAt: now,
            updatedAt: now,
            autoGenerated: true
        )
    }
}

// MARK: - Step 1: 肌群选择
//
// 每个主肌群是一行: 一个大的 major chip + 它的子细分 sub-chips (如有), 子chips 更小更淡
// 用户既能选 "Chest" 整体, 也能精准定位 "Upper Chest" / "Mid Chest" / "Lower Chest"
//
// 子细分参考健身专业领域常用分类:
//   - 胸: 上 / 中 / 下 (Clavicular / Sternocostal / Costal)
//   - 背: 阔背 / 上斜方 / 中斜方 / 下斜方 / 下背
//   - 肩: 前束 / 侧束 / 后束
//   - 核心: 上腹 / 下腹 / 腹斜肌
//   - 二头: 长头 / 短头 / 肱肌
//   - 三头: 长头 / 外侧头 / 内侧头
//   - 股四头: 股直 / 股外 / 股内
//   - 腘绳: 股二头 / 半腱
//   - 臀: 臀大 / 臀中
//   - 小腿: 腓肠 / 比目鱼
private struct QuickMuscleStep: View {
    @Environment(DataStore.self) private var data
    @Binding var selected: Set<MuscleGroup>
    let onNext: () -> Void

    /// 用户在 Settings 是否启用"肌肉细分". 关时 sub chip + helper text 整体隐藏, 只显示 major chip.
    /// 同时 BodyHint 走 coarseOnly = true (合并描边).
    private var detailEnabled: Bool { data.settings.muscleDetailEnabled }

    /// 选中的肌群的协同肌 (淡绿色显示) — 跟随 selected 自动算
    private var synergistsArr: [MuscleGroup] {
        Array(MuscleSynergy.synergists(for: selected))
    }
    /// O(1) 查询 — MuscleSelector 拿来标"带到"色
    private var synergistsSet: Set<MuscleGroup> {
        MuscleSynergy.synergists(for: selected)
    }

    var body: some View {
        VStack(spacing: 0) {
            // 大 BodyHint — 实时反映选中 + 协同肌 (后者淡绿)
            // 不再加底部 mask 渐变 — 身体下沿直接结束, 不淡化掉腿/脚.
            // 现在可以"点身体某块肌肉" → toggle 该肌群 chip 的选中状态.
            // hit-test 落到具体 sub (e.g. upperChest), 用 MuscleSelector.majorOf 折叠回 UI
            // 暴露的 major chip (chest / back / biceps / quads etc.), 让 tap = "选这一整块",
            // 跟 chip 操作语义一致.
            HStack {
                Spacer()
                BodyHint(
                    muscles: Array(selected),
                    synergists: synergistsArr,
                    height: MasoMetrics.bodyHintLarge,
                    // region 也把协同肌算进去 — 选 chest 会带到 triceps, 必须保留 full 视图
                    region: detectBodyRegion(Array(selected) + synergistsArr),
                    onMuscleTap: { m in
                        let key = MuscleSelector.majorOf(m)
                        toggle(key)
                        Haptics.tap()  // 轻触反馈 — 让 tap 操作有"已识别"的感觉
                    },
                    coarseOnly: !detailEnabled
                )
                Spacer()
            }
            .padding(.top, 12)
            .padding(.bottom, 2)

            // 颜色讲解 legend — 跟标题 / chip 一起左对齐 (除了顶部 BodyHint, 其它都靠左).
            legendStrip
                .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
                .padding(.bottom, 6)

            // chip 选区 — 滚动. Header "Target Muscles" + 分组 chip 全部左对齐.
            // 用共享 MuscleSelector — 跟 Onboarding / Settings picker 同一份 UI + 同一份分组,
            // synergists 参数让"训练目标带到的协同肌"在 chip 上半透显示.
            ScrollView {
                VStack(alignment: .leading, spacing: 14) {
                    targetMusclesHeader
                    MuscleSelector(
                        selected: $selected,
                        detailEnabled: detailEnabled,
                        synergists: synergistsSet
                    )
                }
                .frame(maxWidth: .infinity, alignment: .leading)
                .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
                .padding(.vertical, 16)
            }

            // 下一步按钮
            Button(action: onNext) {
                HStack(spacing: 8) {
                    Text(selected.isEmpty
                         ? "Pick at least one muscle"
                         : "Continue (\(selected.count))")
                    if !selected.isEmpty {
                        Image(systemName: "arrow.right")
                            .font(.system(size: 12, weight: .heavy))
                    }
                }
                .font(.system(size: 14, weight: .heavy))
                .frame(maxWidth: .infinity)
                .padding(.vertical, 14)
                .background(selected.isEmpty ? MasoColor.surfaceHi : MasoColor.accent)
                .foregroundStyle(selected.isEmpty ? MasoColor.textDim : .black)
                .clipShape(Capsule())
            }
            .buttonStyle(.plain)
            .disabled(selected.isEmpty)
            .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
            .padding(.bottom, 24)
        }
        // 进入 / detail 切换时统一走 MuscleSelector.sanitize — 清孤儿 sub + 按 detailEnabled 折叠.
        // 避免"看不见的幽灵 sub 残留" 跟 Settings/Onboarding 同一逻辑.
        .onAppear { sanitizeSelection() }
        .onChange(of: data.settings.muscleDetailEnabled) { _, _ in sanitizeSelection() }
    }

    private func sanitizeSelection() {
        let cleaned = MuscleSelector.sanitize(selected, detailEnabled: detailEnabled)
        if cleaned != selected { selected = cleaned }
    }

    // MARK: - Legend (under body image) + section header

    /// 颜色讲解 strip — 放在 BodyHint 正下方靠左 (跟 Target Muscles header / chip 左对齐统一).
    /// 只在用户有选中 (产生协同肌) 时出现, 不抢初始焦点
    @ViewBuilder
    private var legendStrip: some View {
        HStack(spacing: 14) {
            if !synergistsSet.isEmpty {
                legendDot(color: MasoColor.accent, text: "Selected")
                legendDot(color: MasoColor.accent.opacity(0.45),
                          text: "Brought along during training")
            }
            Spacer(minLength: 0)
        }
        .frame(maxWidth: .infinity, alignment: .leading)
        .frame(height: synergistsSet.isEmpty ? 0 : 18)
        .opacity(synergistsSet.isEmpty ? 0 : 1)
        .animation(.easeOut(duration: 0.2), value: synergistsSet)
    }

    private func legendDot(color: Color, text: String) -> some View {
        HStack(spacing: 5) {
            Circle().fill(color).frame(width: 8, height: 8)
            // text 是 "Selected" / "Brought along during training" — 走 LSK 查表
            Text(LocalizedStringKey(text))
                .font(.system(size: 10, weight: .semibold))
                .foregroundStyle(MasoColor.textDim)
        }
    }

    /// "TARGET MUSCLES" 小标题 + 一行 helper 文案解释浅绿色 chip 的意思.
    /// 浅绿色 chip = synergist (协同肌) — 训练主项时会被带到, 用户不用主动选.
    /// 整体左对齐 (跟下面 chip 行起点对齐, 视觉一致).
    @ViewBuilder
    private var targetMusclesHeader: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(NSLocalizedString("Target Muscles", comment: "").uppercased())
                .font(.system(size: 11, weight: .heavy))
                .tracking(1.5)
                .foregroundStyle(MasoColor.textDim)
            Text("Light green = synergist · worked along the way, no need to pick.")
                .font(.system(size: 11))
                .foregroundStyle(MasoColor.textFaint)
                .multilineTextAlignment(.leading)
                .fixedSize(horizontal: false, vertical: true)
        }
    }

    private func toggle(_ m: MuscleGroup) {
        if selected.contains(m) { selected.remove(m) } else { selected.insert(m) }
    }
}

// MARK: - Step 2: 按肌群挑动作

private struct QuickExerciseStep: View {
    @Environment(DataStore.self) private var data
    let selectedMuscles: Set<MuscleGroup>
    @Binding var pickedIds: Set<String>
    /// AI 推荐的顺序 — autoPick AI 路径会 set 它. parent 的 synthesizePlan 用它排 playlist.
    /// 手动改后保留 (不清空) — synthesizePlan 自己处理"AI list 里没有的"额外项.
    @Binding var aiOrder: [String]?
    let exById: [String: Exercise]
    let allExercises: [Exercise]
    let onStart: () -> Void

    /// AI 调用中 — 按钮变 loading state, 不可重复点
    @State private var aiLoading: Bool = false
    /// 错误 toast — AI 不可用时弹一下提示, 仍 fallback 走本地
    @State private var aiFallbackMessage: String? = nil
    /// 器械筛选 (nil = 不限). 跟 Library / Plans picker 一致, 单选 menu.
    @State private var equipmentFilter: String? = nil
    /// 点图片缩略图弹的动作详情 sheet.
    @State private var detailExercise: Exercise? = nil

    var body: some View {
        // 中间动作列表用 ScrollView. 顶部 inset 只放 equipment filter (平铺 badge),
        // 底部 inset 放 Smart pick + Start CTA. 底色全用 MasoColor.background, 不再用
        // 毛玻璃 — 跟 sheet 整体视觉一致, 不抢眼.
        ScrollView {
            VStack(alignment: .leading, spacing: 20) {
                ForEach(orderedMuscles, id: \.self) { m in
                    section(for: m)
                }
            }
            .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
            .padding(.vertical, 12)
        }
        // 顶部 — equipment filter, 平铺 badge (横向滚动). 不再显示已选肌群 chips
        // (已经在 Step 1 选过 + 这页按 muscle 分组的 section header 已经展示, 冗余).
        .safeAreaInset(edge: .top, spacing: 0) {
            equipmentBadgeRow
                .padding(.vertical, 10)
                .background(MasoColor.background)
        }
        // 底部 — Smart pick + Start CTA, 上方有透明渐变让滚动内容自然过渡进毛玻璃
        .safeAreaInset(edge: .bottom, spacing: 0) {
            HStack(spacing: 10) {
                smartPickButton
                startButton
            }
            .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
            .padding(.top, 20)     // 顶部多留白, 跟 scroll 内容隔开
            .padding(.bottom, 16)
            .background(
                MasoColor.background
                    .ignoresSafeArea(edges: .bottom)
            )
        }
        // 点图片缩略图 → 弹动作详情 (跟 Library / Picker 同款 ExerciseDetailSheet, 纯浏览模式)
        .sheet(item: $detailExercise) { ex in
            ExerciseDetailSheet(exercise: ex)
        }
    }

    /// Equipment 筛选 badge 行 — 横向滚动, 每个器械一个 badge, 可点切换 (实心 accent = 已选,
    /// 灰底 = 未选). 跟 menu 模式比, 平铺让用户一眼看到所有选项 + 直接 tap 切换, 不需多一次"打开
    /// 菜单"的交互. "Any" badge 在最左, 选它 = 清空 filter.
    private var equipmentBadgeRow: some View {
        let avail = availableEquipments
        return ScrollView(.horizontal, showsIndicators: false) {
            HStack(spacing: 6) {
                equipmentBadge(
                    label: NSLocalizedString("Any equipment", comment: ""),
                    selected: equipmentFilter == nil,
                    enabled: true,
                    action: { equipmentFilter = nil }
                )
                ForEach(Exercise.knownEquipments, id: \.self) { eq in
                    let isSel = equipmentFilter == eq
                    let isEnabled = avail.contains(eq) || isSel
                    equipmentBadge(
                        label: Exercise.equipmentDisplayName(for: eq),
                        selected: isSel,
                        enabled: isEnabled,
                        action: {
                            // 再点已选 = 取消; 否则切换到这个
                            equipmentFilter = isSel ? nil : eq
                        }
                    )
                }
            }
            .padding(.horizontal, MasoMetrics.pagePaddingHorizontal)
        }
    }

    private func equipmentBadge(label: String, selected: Bool, enabled: Bool, action: @escaping () -> Void) -> some View {
        Button(action: action) {
            Text(label)
                .font(.system(size: 12, weight: .heavy))
                .padding(.horizontal, 12).padding(.vertical, 6)
                .background(selected ? MasoColor.accent : MasoColor.surface)
                .foregroundStyle(selected ? .black : MasoColor.textDim)
                .clipShape(Capsule())
                .opacity(enabled || selected ? 1 : 0.35)
        }
        .buttonStyle(.plain)
        .disabled(!enabled && !selected)
    }

    /// 两个 CTA 等高常量 — 不靠 padding 计算, 显式 .frame(height) 兜底
    private static let ctaHeight: CGFloat = 50

    /// AI 智能推荐 — 轻 accent 浅底 + 描边. fit-to-content (sparkles + 短文案), 不撑满.
    /// 跟主 CTA Start 同行同高 (都用 ctaHeight 显式锁), 视觉地位"次于但同级".
    @ViewBuilder
    private var smartPickButton: some View {
        Button(action: { Task { await autoPick() } }) {
            HStack(spacing: 6) {
                if aiLoading {
                    ProgressView()
                        .scaleEffect(0.7)
                        .tint(MasoColor.accent)
                        .frame(width: 16, height: 16)
                } else {
                    Image(systemName: "sparkles")
                        .font(.system(size: 14, weight: .heavy))
                }
                Text(aiLoading ? NSLocalizedString("Asking the coach…", comment: "") : NSLocalizedString("Smart pick", comment: ""))
                    .font(.system(size: 14, weight: .bold))
                    .lineLimit(1)
            }
            .foregroundStyle(MasoColor.accent)
            .padding(.horizontal, 16)
            .frame(height: Self.ctaHeight)
            .background(MasoColor.accent.opacity(0.12))
            .overlay(
                Capsule().stroke(MasoColor.accent.opacity(0.4), lineWidth: 0.8)
            )
            .clipShape(Capsule())
        }
        .buttonStyle(.plain)
        .disabled(aiLoading)
        // AI fallback 到本地的提示 alert — 之前挂在 autoPickBanner, 删 banner 后移到这.
        .alert(
            "Using local picker",
            isPresented: Binding(
                get: { aiFallbackMessage != nil },
                set: { if !$0 { aiFallbackMessage = nil } }
            )
        ) {
            Button("OK") { aiFallbackMessage = nil }
        } message: {
            Text(aiFallbackMessage ?? "")
        }
    }

    /// 主 CTA — Start 训练. 占行剩余宽度 (maxWidth infinity), 跟 smartPick 等高.
    @ViewBuilder
    private var startButton: some View {
        Button(action: onStart) {
            HStack(spacing: 8) {
                Image(systemName: "play.fill")
                Text(pickedIds.isEmpty
                     ? "Pick at least one exercise"
                     : "Start (\(pickedIds.count))")
            }
            .font(.system(size: 14, weight: .heavy))
            .frame(maxWidth: .infinity)
            .frame(height: Self.ctaHeight)
            .background(pickedIds.isEmpty ? MasoColor.surfaceHi : MasoColor.accent)
            .foregroundStyle(pickedIds.isEmpty ? MasoColor.textDim : .black)
            .clipShape(Capsule())
        }
        .buttonStyle(.plain)
        .disabled(pickedIds.isEmpty)
    }

    /// 选中肌群按主肌群预定义顺序排.
    ///
    /// 关键点: 用户在 Step 1 可能只选了 sub-muscle (例 upperChest, bicepsLong),
    /// 没选 major (chest, biceps). 之前直接 `selectedMuscles.contains(.chest)`
    /// 返回 false → orderedMuscles 空 → Step 2 整页空白.
    /// 修复: 把每个 selected sub 折叠回它的 major chip 对应 group, 再过滤 order.
    private var orderedMuscles: [MuscleGroup] {
        let order: [MuscleGroup] = [.chest, .back, .shoulders, .biceps, .triceps,
                                    .forearms, .core, .quads, .hamstrings, .glutes, .calves, .adductors]
        // 用共享 MuscleSelector.majorOf — 全 app 肌群归一的唯一入口.
        // 之前这里维护一份独立 majorFor switch, 跟 MuscleSelector / WorkoutCard 重复了 3 份,
        // 修改分组规则要改 3 处. 现在合一.
        let majors: Set<MuscleGroup> = Set(selectedMuscles.map { MuscleSelector.majorOf($0) })
        return order.filter { majors.contains($0) }
    }

    /// Pro + AI 配好 → 走 AI 路径; 否则走本地启发式
    private var useAIPath: Bool {
        data.settings.isPro
            && data.settings.aiWorkoutEnabled
            && AIWorkoutService.isConfigured
    }

    /// 智能推荐 — Pro + AI 启用走 AI, 失败 fallback 本地; 非 Pro 直接本地.
    ///   - AI 路径: 把 user profile + 14d history + selected muscles + 候选库传 DeepSeek, 返回 ordered IDs
    ///   - 本地 fallback: 每个 selected major muscle 取 top-2, 总数 cap 8
    /// 都是覆盖 pickedIds, 不是追加 — 干净起步, 用户事后能手点增删.
    @MainActor
    private func autoPick() async {
        if useAIPath {
            await autoPickViaAI()
        } else {
            autoPickLocal()
        }
    }

    /// AI 路径 — 异步, 失败静默 fallback 本地并提示用户
    @MainActor
    private func autoPickViaAI() async {
        aiLoading = true
        defer { aiLoading = false }

        // 1. 准备候选集 — 每个肌群 top-6 动作 (跟用户能看到的列表一致), 跨肌群 dedupe
        var candidateIds = Set<String>()
        var candidates: [Exercise] = []
        for m in orderedMuscles {
            for scored in topExercises(for: m) {
                if candidateIds.insert(scored.exercise.id).inserted {
                    candidates.append(scored.exercise)
                }
            }
        }
        // cap 40 — DeepSeek prompt size 控制
        if candidates.count > 40 {
            candidates = Array(candidates.prefix(40))
        }

        // 2. 构 payload — 跟 generateToday 同一个 helper
        let payload = data.buildAIPayload()

        // 3. 调 AI
        let muscleNames = orderedMuscles.map { $0.displayName }
        let result = await AIWorkoutService.shared.pickFreeWorkoutExercises(
            payload: payload,
            targetMuscles: muscleNames,
            candidates: candidates
        )

        // 4. 处理结果
        if let orderedIds = result, !orderedIds.isEmpty {
            pickedIds = Set(orderedIds)
            aiOrder = orderedIds  // 给 synthesizePlan 用 — playlist 按 AI 顺序排
        } else {
            // AI 失败 → fallback 本地 + 提示用户
            autoPickLocal()
            aiFallbackMessage = "Couldn't reach the AI coach. Using a local recommendation instead."
        }
    }

    /// 本地启发式 — 每个 muscle 取 top-2, 总 cap 8
    private func autoPickLocal() {
        var picked: [String] = []
        let perMuscleCap = 2
        let totalCap = 8
        for m in orderedMuscles {
            let top = topExercises(for: m).prefix(perMuscleCap)
            for scored in top {
                if !picked.contains(scored.exercise.id) {
                    picked.append(scored.exercise.id)
                    if picked.count >= totalCap { break }
                }
            }
            if picked.count >= totalCap { break }
        }
        pickedIds = Set(picked)
        aiOrder = picked  // 本地排序也走 picked 的顺序, 让 playlist 按 muscle 顺序排
    }

    /// 每个肌群一个 section: 标题 + top-N 推荐动作
    @ViewBuilder
    private func section(for muscle: MuscleGroup) -> some View {
        VStack(alignment: .leading, spacing: 8) {
            HStack {
                Text(muscle.displayName.uppercased())
                    .font(.system(size: 10, weight: .heavy))
                    .tracking(1.5)
                    .foregroundStyle(MasoColor.accent)
                Spacer()
                let pickedInThisMuscle = pickedIds.intersection(Set(topExercises(for: muscle).map { $0.exercise.id })).count
                if pickedInThisMuscle > 0 {
                    Text("\(pickedInThisMuscle) picked")
                        .font(.system(size: 10, weight: .bold))
                        .foregroundStyle(MasoColor.textDim)
                }
            }
            VStack(spacing: 6) {
                ForEach(topExercises(for: muscle), id: \.exercise.id) { scored in
                    exerciseRow(scored)
                }
            }
        }
    }

    private func exerciseRow(_ scored: ScoredExercise) -> some View {
        let ex = scored.exercise
        let picked = pickedIds.contains(ex.id)
        // 视觉跟"训练中" InlinePlaylist.playlistRow 完全对齐 — 全 app 动作行统一规格.
        // 唯一不同: trailing 区有 MatchBadge + picked indicator (保留 picker 特有的交互).
        // 双 hit-zone: 图片是独立 Button (tap → 详情), 整行其余区域 onTapGesture 切 picked.
        return HStack(spacing: 14) {
            Button(action: { detailExercise = ex }) {
                ExerciseImage(
                    category: ex.category,
                    imageFolder: ex.imageFolder,
                    cornerRadius: 8,
                    size: 56,
                    animated: false
                )
            }
            .buttonStyle(.plain)
            .accessibilityLabel(String(format: NSLocalizedString("Show details for %@", comment: "exercise detail a11y"), ex.displayName))

            VStack(alignment: .leading, spacing: 5) {
                Text(ex.displayName)
                    .font(.system(size: 15, weight: .bold))
                    .foregroundStyle(MasoColor.text)
                    .lineLimit(1)
                // muscleLimit 0 — 这页按 muscle section 分组渲染, muscle 信息冗余, 只显 equipment.
                ExerciseTagsRow(
                    muscleGroups: ex.muscleGroups,
                    equipment: ex.equipment,
                    muscleLimit: 0
                )
            }
            .frame(maxWidth: .infinity, alignment: .leading)
            // 收藏标记 — 排序已经把 favorites 置顶, 这里再加 icon 视觉确认
            if data.isFavorite(ex.id) {
                Image(systemName: "heart.fill")
                    .font(.system(size: 12, weight: .heavy))
                    .foregroundStyle(MasoColor.accent)
            }
            // 匹配度 badge — 跟 web 的 MatchBadge 一致
            MatchBadge(score: scored.score)
            // 选中状态
            Image(systemName: picked ? "checkmark.circle.fill" : "plus.circle")
                .font(.system(size: 20, weight: .semibold))
                .foregroundStyle(picked ? MasoColor.accent : MasoColor.textFaint)
        }
        .padding(.horizontal, MasoMetrics.rowPaddingH)
        .padding(.vertical, 10)
        .background(picked ? MasoColor.accent.opacity(0.10) : MasoColor.surface)
        .overlay(
            RoundedRectangle(cornerRadius: 14)
                .stroke(picked ? MasoColor.accent.opacity(0.4) : Color.clear, lineWidth: 1)
        )
        .clipShape(RoundedRectangle(cornerRadius: 14))
        // tap 行其它区域 → toggle picked. 图片那块 Button 优先级更高, 不会触发这个.
        .contentShape(Rectangle())
        .onTapGesture {
            if picked { pickedIds.remove(ex.id) } else { pickedIds.insert(ex.id) }
        }
    }

    /// 给定 muscle, 找到匹配度 top-6 的 strength + cardio + flexibility 动作 (应用 equipment 筛选)
    private func topExercises(for muscle: MuscleGroup) -> [ScoredExercise] {
        // 展开 → 子肌群 (例: chest → [chest, upperChest, midChest, lowerChest])
        let targets = expandAnatomyMuscles([muscle])
        // 候选先过 equipment filter, 再打分
        let candidates: [Exercise] = allExercises.filter { matchesEquipment($0) }
        let scored: [ScoredExercise] = candidates.compactMap { ex in
            let s = score(ex, against: targets)
            return s > 0 ? ScoredExercise(exercise: ex, score: s) : nil
        }
        // 收藏前置 + match score 排序 — favorites 在前 (内部按 score 排), non-favorites 在后 (按 score 排).
        let favSet = Set(data.settings.favoriteExerciseIds)
        let favs = scored.filter { favSet.contains($0.exercise.id) }
            .sorted { $0.score > $1.score }
        let rest = scored.filter { !favSet.contains($0.exercise.id) }
            .sorted { $0.score > $1.score }
        return Array((favs + rest).prefix(6))
    }

    /// equipment filter 命中? nil = 任何器械都行.
    private func matchesEquipment(_ ex: Exercise) -> Bool {
        guard let eq = equipmentFilter else { return true }
        if eq == "other" { return ex.equipment == "other" || ex.equipment == nil }
        return ex.equipment == eq
    }

    /// 当前已选肌群下还有动作的 equipment set — menu 里 dim disabled 用.
    private var availableEquipments: Set<String> {
        var out: Set<String> = []
        // 只看在 selectedMuscles 任何一项下有匹配的动作; equipment 维度先不限.
        for ex in allExercises {
            var hits = false
            for m in selectedMuscles {
                let targets = expandAnatomyMuscles([m])
                if score(ex, against: targets) > 0 { hits = true; break }
            }
            guard hits else { continue }
            out.insert(ex.equipment ?? "other")
        }
        return out
    }

    /// score 公式跟 web 的 scoreExercise 对齐: Σ max(20, 100 - idx*18)
    private func score(_ ex: Exercise, against targets: Set<MuscleGroup>) -> Int {
        var total = 0
        for (idx, mg) in ex.muscleGroups.enumerated() {
            if targets.contains(mg) {
                total += max(20, 100 - idx * 18)
            }
        }
        return total
    }
}

private struct ScoredExercise: Hashable {
    let exercise: Exercise
    let score: Int
}

/// 匹配度小 badge — 数字 + accent 描边
private struct MatchBadge: View {
    let score: Int
    private var pct: Int { min(100, score * 100 / 120) }  // 校准: 单命中 100 分 → ~83%
    var body: some View {
        Text("\(pct)%")
            .font(.system(size: 10, weight: .heavy).monospacedDigit())
            .foregroundStyle(MasoColor.accent)
            .padding(.horizontal, 6).padding(.vertical, 2)
            .background(MasoColor.accent.opacity(0.12))
            .clipShape(Capsule())
    }
}
