import SwiftUI
import UIKit

// 训练完成分享卡 (详情版) — 对照第三方"训记"风格: 日期 + 肌肉图 + 三项汇总数据 +
// 逐组实测明细 (动作名 + 每组 "Wkg × reps") + 品牌 footer 带 maso:// 深链 QR.
//
// 关键: 卡片所见 == 导入所得. WorkoutShareBuilder 从本次 session 的 SetRecord 同时产出
//   (1) 这张卡的逐组明细, (2) 编进 QR 的可导入 Plan (含逐组 setWeights/setReps).
// 收到图的人回 App 用"从照片导入"扫这个 QR → PlanShareCodec 无损还原同一份 routine.

/// 一个动作的逐组实测明细 (分享卡渲染 + builder 产出).
struct WorkoutExerciseDetail: Identifiable {
    let id: String          // exerciseId
    let name: String
    let sets: [PerformedSet]
    struct PerformedSet {
        var weight: Double?
        var reps: Int?
        var duration: Int?  // 计时类动作 (秒); 力量类为 nil
    }
}

// MARK: - Builder — session SetRecord → (明细, 可导入 Plan)

enum WorkoutShareBuilder {
    /// 从本次训练实际完成的 SetRecord 构造明细 + 可导入 Plan.
    /// - sessionSets: 已过滤到本次 session 的 SetRecord (按任意顺序, 内部按 performedAt 排).
    /// - orderHint: plan.steps — 用来定动作展示顺序; 没有则按 set 首次出现顺序.
    /// 返回的 Plan 每个动作 = 一个 step, sets = 实测组数, setWeights/setReps = 逐组实测值.
    static func build(
        sessionSets: [SetRecord],
        orderHint: [PlanStep],
        exById: [String: Exercise],
        planName: String
    ) -> (detail: [WorkoutExerciseDetail], importPlan: Plan) {
        let sorted = sessionSets.sorted { $0.performedAt < $1.performedAt }
        // 按 exerciseId 分桶 (保持 performedAt 顺序)
        var grouped: [String: [SetRecord]] = [:]
        var firstSeen: [String] = []
        for rec in sorted {
            if grouped[rec.exerciseId] == nil { firstSeen.append(rec.exerciseId) }
            grouped[rec.exerciseId, default: []].append(rec)
        }
        // 动作顺序: 优先 plan.steps (去重), 没在 plan 里的 (训练中临时加的) 接在后面
        var order: [String] = []
        var seen = Set<String>()
        for step in orderHint where grouped[step.exerciseId] != nil && seen.insert(step.exerciseId).inserted {
            order.append(step.exerciseId)
        }
        for exId in firstSeen where seen.insert(exId).inserted {
            order.append(exId)
        }

        var detail: [WorkoutExerciseDetail] = []
        var steps: [PlanStep] = []
        for (idx, exId) in order.enumerated() {
            guard let recs = grouped[exId], !recs.isEmpty else { continue }
            let name = exById[exId]?.displayName ?? recs.first?.exerciseName ?? exId
            let perfSets = recs.map {
                WorkoutExerciseDetail.PerformedSet(weight: $0.weight, reps: $0.reps, duration: $0.duration)
            }
            detail.append(WorkoutExerciseDetail(id: exId, name: name, sets: perfSets))

            // 可导入 step. 关键: 逐组数组只在"组间真有差异"时才保留 —— 常见的同重同次
            // ([60,60,60,60]) 折叠回 reps/weight 统一值. 不折叠的话 QR payload 随组数膨胀,
            // 大训练的二维码会密到扫不出 (审查发现). collapsed nil + 统一值 → import 展开同样 N 组.
            let reps: [Int?] = recs.map(\.reps)
            let weights: [Double?] = recs.map(\.weight)
            let durations = recs.compactMap(\.duration)
            steps.append(PlanStep(
                id: "step-\(exId)-\(idx)",
                exerciseId: exId,
                sets: recs.count,
                reps: reps.compactMap { $0 }.first,
                weight: weights.compactMap { $0 }.first,
                setReps: Self.collapseUniform(reps),
                setWeights: Self.collapseUniform(weights),
                duration: durations.first,
                restBetweenSets: 90,
                rest: 0
            ))
        }

        return (detail, makeImportPlan(steps: steps, planName: planName))
    }

    /// 逐组数组 → 折叠: 全组同一个非 nil 值 (或全 nil) → nil (走统一 reps/weight, payload 省一截);
    /// 真有差异 → 原样保留 (逐组 import 还原).
    private static func collapseUniform<T: Equatable>(_ arr: [T?]) -> [T?]? {
        guard arr.contains(where: { $0 != nil }) else { return nil }
        let first = arr.first ?? nil
        return arr.allSatisfy { $0 == first } ? nil : arr
    }

    private static func makeImportPlan(steps: [PlanStep], planName: String) -> Plan {
        let plan = Plan(
            id: "shared-\(Int(Date().timeIntervalSince1970))",
            name: planName.isEmpty ? NSLocalizedString("Shared workout", comment: "imported workout default name") : planName,
            steps: steps,
            createdAt: Date(),
            updatedAt: Date(),
            autoGenerated: false
        )
        return plan
    }
}

// MARK: - 卡片

struct WorkoutDetailShareCard: View {
    /// 日期行 (e.g. "2026-06-09 周二" / "Mon, Jun 9"). nil = 不显示.
    var dateLabel: String? = nil
    let planName: String
    let muscles: [MuscleGroup]
    let detail: [WorkoutExerciseDetail]
    /// 汇总: 总组数 / 总容量 (kg) / 时长文案.
    let setCount: Int
    let totalVolumeKg: Double
    let durationLabel: String
    /// maso:// 深链 — 进 footer 的 QR. nil = 不画 QR (无法构造时).
    let qrPayload: String?
    var userPhoto: UIImage? = nil
    var onTapAddPhoto: (() -> Void)? = nil

    private var volumeLabel: String {
        if totalVolumeKg <= 0 { return "0" }
        let v = totalVolumeKg
        return v.truncatingRemainder(dividingBy: 1) == 0 ? String(format: "%.0f", v) : String(format: "%.1f", v)
    }

    var body: some View {
        VStack(spacing: 0) {
            SharePhotoBanner(photo: userPhoto, onTapToAdd: onTapAddPhoto)

            VStack(alignment: .leading, spacing: 18) {
                // 头部 — 日期 kicker + 计划名
                VStack(alignment: .leading, spacing: 6) {
                    if let dateLabel {
                        Text(dateLabel)
                            .font(.system(size: 11, weight: .bold))
                            .tracking(0.5)
                            .foregroundStyle(MasoColor.textDim)
                    }
                    Text(planName.isEmpty ? NSLocalizedString("Free workout", comment: "") : planName)
                        .font(.system(size: 22, weight: .heavy))
                        .foregroundStyle(MasoColor.text)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(.top, userPhoto == nil ? 6 : 0)

                // 肌肉图 (前+后) 居中
                if !muscles.isEmpty {
                    HStack {
                        Spacer(minLength: 0)
                        MuscleVisualBlock(muscles: muscles, sideLength: 150)
                            .frame(width: 150, height: 150)
                        Spacer(minLength: 0)
                    }
                }

                // 三项汇总数据
                HStack(spacing: 24) {
                    ShareStat(value: "\(setCount)", label: NSLocalizedString("Sets", comment: ""))
                    ShareStat(value: volumeLabel, label: NSLocalizedString("Volume kg", comment: "total lifted volume"))
                    ShareStat(value: durationLabel, label: NSLocalizedString("Duration", comment: ""))
                    Spacer(minLength: 0)
                }

                Rectangle().fill(MasoColor.borderSoft).frame(height: 0.5)

                // 逐组实测明细 — 每个动作: 名字 + 4 列网格的每组值
                VStack(alignment: .leading, spacing: 16) {
                    ForEach(detail) { ex in
                        VStack(alignment: .leading, spacing: 8) {
                            Text(ex.name)
                                .font(.system(size: 16, weight: .bold))
                                .foregroundStyle(MasoColor.text)
                                .lineLimit(1)
                            ForEach(Array(setRows(ex.sets).enumerated()), id: \.offset) { _, row in
                                HStack(spacing: 0) {
                                    ForEach(row, id: \.index) { cell in
                                        HStack(spacing: 5) {
                                            Text("\(cell.index)")
                                                .font(.system(size: 11, weight: .semibold).monospacedDigit())
                                                .foregroundStyle(MasoColor.textFaint)
                                            Text(cell.text)
                                                .font(.system(size: 13).monospacedDigit())
                                                .foregroundStyle(MasoColor.textDim)
                                        }
                                        .frame(maxWidth: .infinity, alignment: .leading)
                                    }
                                    // 补齐不足 4 列的空位, 保持左对齐
                                    if row.count < 4 {
                                        ForEach(0..<(4 - row.count), id: \.self) { _ in
                                            Color.clear.frame(maxWidth: .infinity)
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            .padding(.horizontal, 22)
            .padding(.top, userPhoto == nil ? 22 : 18)
            .padding(.bottom, 20)
            .frame(maxWidth: .infinity, alignment: .leading)

            // QR 放大到 104pt — 分享卡被转发/压缩后仍能扫 (审查发现 76pt 在重压缩后密度不足).
            ShareCardFooter(qrPayload: qrPayload, qrSize: 104)
        }
        .background(MasoColor.background)
    }

    /// 把一个动作的若干组切成每行最多 4 个的网格, 每格带 1-based 组号 + 显示文案.
    private struct SetCell { let index: Int; let text: String }
    private func setRows(_ sets: [WorkoutExerciseDetail.PerformedSet]) -> [[SetCell]] {
        let cells = sets.enumerated().map { i, s in SetCell(index: i + 1, text: cellText(s)) }
        return stride(from: 0, to: cells.count, by: 4).map { Array(cells[$0..<min($0 + 4, cells.count)]) }
    }

    private func cellText(_ s: WorkoutExerciseDetail.PerformedSet) -> String {
        // 计时类 (无 reps, 有 duration) → "30s"; 力量类 → "Wkg × reps".
        if s.reps == nil, let d = s.duration, d > 0 {
            return d >= 60 ? "\(d / 60)m\(d % 60 == 0 ? "" : " \(d % 60)s")" : "\(d)s"
        }
        let w = s.weight ?? 0
        let wStr = w.truncatingRemainder(dividingBy: 1) == 0 ? String(format: "%.0f", w) : String(format: "%.1f", w)
        let reps = s.reps ?? 0
        return "\(wStr)kg × \(reps)"
    }
}
