import SwiftUI
import UIKit

// 训练完成分享卡 (详情版) — 对照第三方"训记"风格: 日期 + 肌肉图 + 三项汇总数据 +
// 逐组实测明细 (动作名 + 每组 "Wkg × reps") + 品牌 footer 带 maso:// 深链 QR.
//
// 关键: 卡片所见 == 导入所得. WorkoutShareBuilder 从本次 session 的 SetRecord 同时产出
//   (1) 这张卡的逐组明细, (2) 编进 QR 的可导入 Plan (含逐组 setWeights/setReps).
// 收到图的人回 App 用"从照片导入"扫这个 QR → PlanShareCodec 无损还原同一份 routine.

/// 一个动作的逐组实测明细 (分享卡渲染 + builder 产出).
struct WorkoutExerciseDetail: Identifiable {
    let id: String          // exerciseId
    let name: String
    let sets: [PerformedSet]
    struct PerformedSet {
        var weight: Double?
        var reps: Int?
        var duration: Int?  // 计时类动作 (秒); 力量类为 nil
    }
}

// MARK: - Builder — session SetRecord → (明细, 可导入 Plan)

enum WorkoutShareBuilder {
    /// 从本次训练实际完成的 SetRecord 构造明细 + 可导入 Plan.
    /// - sessionSets: 已过滤到本次 session 的 SetRecord (按任意顺序, 内部按 performedAt 排).
    /// - orderHint: plan.steps — 用来定动作展示顺序; 没有则按 set 首次出现顺序.
    /// 返回的 Plan 每个动作 = 一个 step, sets = 实测组数, setWeights/setReps = 逐组实测值.
    static func build(
        sessionSets: [SetRecord],
        orderHint: [PlanStep],
        exById: [String: Exercise],
        planName: String
    ) -> (detail: [WorkoutExerciseDetail], importPlan: Plan) {
        let sorted = sessionSets.sorted { $0.performedAt < $1.performedAt }
        // 按 exerciseId 分桶 (保持 performedAt 顺序)
        var grouped: [String: [SetRecord]] = [:]
        var firstSeen: [String] = []
        for rec in sorted {
            if grouped[rec.exerciseId] == nil { firstSeen.append(rec.exerciseId) }
            grouped[rec.exerciseId, default: []].append(rec)
        }
        // 动作顺序: 优先 plan.steps (去重), 没在 plan 里的 (训练中临时加的) 接在后面
        var order: [String] = []
        var seen = Set<String>()
        for step in orderHint where grouped[step.exerciseId] != nil && seen.insert(step.exerciseId).inserted {
            order.append(step.exerciseId)
        }
        for exId in firstSeen where seen.insert(exId).inserted {
            order.append(exId)
        }

        var detail: [WorkoutExerciseDetail] = []
        var steps: [PlanStep] = []
        for (idx, exId) in order.enumerated() {
            guard let recs = grouped[exId], !recs.isEmpty else { continue }
            let name = exById[exId]?.displayName ?? recs.first?.exerciseName ?? exId
            let perfSets = recs.map {
                WorkoutExerciseDetail.PerformedSet(weight: $0.weight, reps: $0.reps, duration: $0.duration)
            }
            detail.append(WorkoutExerciseDetail(id: exId, name: name, sets: perfSets))

            // 可导入 step. 关键: 逐组数组只在"组间真有差异"时才保留 —— 常见的同重同次
            // ([60,60,60,60]) 折叠回 reps/weight 统一值. 不折叠的话 QR payload 随组数膨胀,
            // 大训练的二维码会密到扫不出 (审查发现). collapsed nil + 统一值 → import 展开同样 N 组.
            let reps: [Int?] = recs.map(\.reps)
            let weights: [Double?] = recs.map(\.weight)
            // 逐组保留 nil (index 对齐), 跟 reps/weights 同套折叠逻辑 —— 计时类动作中途改过某组时长
            // (60s/45s/30s) 才会留下 setDurations, 全组同时长则折叠回统一 duration. 不 index 对齐
            // (compactMap) 会让 QR 导入后逐组时长错位.
            let durations: [Int?] = recs.map(\.duration)
            steps.append(PlanStep(
                id: "step-\(exId)-\(idx)",
                exerciseId: exId,
                sets: recs.count,
                reps: reps.compactMap { $0 }.first,
                weight: weights.compactMap { $0 }.first,
                setReps: Self.collapseUniform(reps),
                setWeights: Self.collapseUniform(weights),
                setDurations: Self.collapseUniform(durations),
                duration: durations.compactMap { $0 }.first,
                restBetweenSets: 90,
                rest: 0
            ))
        }

        return (detail, makeImportPlan(steps: steps, planName: planName))
    }

    /// 逐组数组 → 折叠: 全组同一个非 nil 值 (或全 nil) → nil (走统一 reps/weight, payload 省一截);
    /// 真有差异 → 原样保留 (逐组 import 还原).
    private static func collapseUniform<T: Equatable>(_ arr: [T?]) -> [T?]? {
        guard arr.contains(where: { $0 != nil }) else { return nil }
        let first = arr.first ?? nil
        return arr.allSatisfy { $0 == first } ? nil : arr
    }

    private static func makeImportPlan(steps: [PlanStep], planName: String) -> Plan {
        let plan = Plan(
            id: "shared-\(Int(Date().timeIntervalSince1970))",
            name: planName.isEmpty ? NSLocalizedString("Shared workout", comment: "imported workout default name") : planName,
            steps: steps,
            createdAt: Date(),
            updatedAt: Date(),
            autoGenerated: false
        )
        return plan
    }
}

// MARK: - 卡片

struct WorkoutDetailShareCard: View {
    /// 日期行 (e.g. "2026-06-09 周二" / "Mon, Jun 9"). nil = 不显示.
    var dateLabel: String? = nil
    let planName: String
    let muscles: [MuscleGroup]
    let detail: [WorkoutExerciseDetail]
    /// 汇总: 总组数 / 总容量 (kg) / 时长文案.
    let setCount: Int
    let totalVolumeKg: Double
    let durationLabel: String
    /// maso:// 深链 — 进 footer 的 QR. nil = 不画 QR (无法构造时).
    let qrPayload: String?
    var userPhoto: UIImage? = nil
    var onTapAddPhoto: (() -> Void)? = nil

    private var volumeLabel: String {
        if totalVolumeKg <= 0 { return "0" }
        let v = totalVolumeKg
        return v.truncatingRemainder(dividingBy: 1) == 0 ? String(format: "%.0f", v) : String(format: "%.1f", v)
    }

    var body: some View {
        VStack(spacing: 0) {
            SharePhotoBanner(photo: userPhoto, onTapToAdd: onTapAddPhoto)

            VStack(alignment: .leading, spacing: 18) {
                // 头部 — 日期 kicker + 计划名
                VStack(alignment: .leading, spacing: 6) {
                    if let dateLabel {
                        Text(dateLabel)
                            .font(.system(size: 11, weight: .bold))
                            .tracking(0.5)
                            .foregroundStyle(MasoColor.textDim)
                    }
                    Text(planName.isEmpty ? NSLocalizedString("Free workout", comment: "") : planName)
                        .font(.system(size: 22, weight: .heavy))
                        .foregroundStyle(MasoColor.text)
                        .fixedSize(horizontal: false, vertical: true)
                }
                .padding(.top, userPhoto == nil ? 6 : 0)

                // 肌肉图 (前+后) 居中
                if !muscles.isEmpty {
                    HStack {
                        Spacer(minLength: 0)
                        MuscleVisualBlock(muscles: muscles, sideLength: 150)
                            .frame(width: 150, height: 150)
                        Spacer(minLength: 0)
                    }
                }

                // 三项汇总数据
                HStack(spacing: 24) {
                    ShareStat(value: "\(setCount)", label: NSLocalizedString("Sets", comment: ""))
                    ShareStat(value: volumeLabel, label: NSLocalizedString("Volume kg", comment: "total lifted volume"))
                    ShareStat(value: durationLabel, label: NSLocalizedString("Duration", comment: ""))
                    Spacer(minLength: 0)
                }

                Rectangle().fill(MasoColor.borderSoft).frame(height: 0.5)

                // 动作清单 — 每个动作一行: 全名 (不截断) + "组数 × 次数 (· 配重)".
                // OCR 友好格式且全名完整: 收图的人 "从照片导入" 时, OCR 逐行读出动作名 + 组数/次数
                // 还原本次训练 (QR 现在是 App Store 下载链, 不再承担导入). 跟 RoutineShareCard 统一.
                VStack(alignment: .leading, spacing: 12) {
                    ForEach(detail) { ex in
                        HStack(alignment: .firstTextBaseline, spacing: 10) {
                            Text(ex.name)
                                .font(.system(size: 15, weight: .semibold))
                                .foregroundStyle(MasoColor.text)
                                .fixedSize(horizontal: false, vertical: true)
                            Spacer(minLength: 12)
                            Text(exSummary(ex.sets))
                                .font(.system(size: 14).monospacedDigit())
                                .foregroundStyle(MasoColor.textDim)
                                .layoutPriority(1)
                        }
                    }
                }
            }
            .padding(.horizontal, 22)
            .padding(.top, userPhoto == nil ? 22 : 18)
            .padding(.bottom, 20)
            .frame(maxWidth: .infinity, alignment: .leading)

            // QR 放大到 104pt — 分享卡被转发/压缩后仍能扫 (审查发现 76pt 在重压缩后密度不足).
            ShareCardFooter(qrPayload: qrPayload, qrSize: 104)
        }
        .background(MasoColor.background)
    }

    /// 一个动作的本次概要 — OCR 友好: "N × M" (组 × 次), 配重加 "· W kg", 计时类 "N × 30s".
    /// 用众数 (最常见的 reps/weight) 当代表值 (各组若有出入, 取做得最多的那档), 单行可被 OCR 解析还原.
    private func exSummary(_ sets: [WorkoutExerciseDetail.PerformedSet]) -> String {
        let n = sets.count
        // 计时类 (全部组都无 reps, 有 duration)
        if sets.allSatisfy({ $0.reps == nil }), let d = mode(sets.compactMap { $0.duration }), d > 0 {
            let dur = d >= 60 ? "\(d / 60)m\(d % 60 == 0 ? "" : " \(d % 60)s")" : "\(d)s"
            return "\(n) × \(dur)"
        }
        let reps = mode(sets.compactMap { $0.reps }) ?? 0
        var out = "\(n) × \(reps)"
        if let w = mode(sets.compactMap { $0.weight }.filter { $0 > 0 }), w > 0 {
            let wStr = w.truncatingRemainder(dividingBy: 1) == 0 ? String(format: "%.0f", w) : String(format: "%.1f", w)
            out += " · \(wStr) kg"
        }
        return out
    }

    /// 众数 (出现次数最多的值); 平局取任一; 空 → nil.
    private func mode<T: Hashable>(_ xs: [T]) -> T? {
        var counts: [T: Int] = [:]
        for x in xs { counts[x, default: 0] += 1 }
        return counts.max(by: { $0.value < $1.value })?.key
    }
}
