import Foundation
import Observation
import SwiftUI

// 训练会话 — 全局状态, 跟 web 端 trainingSession.tsx 1:1 对齐
//
// 关键不变量:
//   - 同一时间只有一条 session
//   - playing + endsAt 一起表达 "自动倒计时"
//   - pausedRemaining 在暂停时保存剩余秒数, 恢复时变回 endsAt
//   - segmentIndex 越界时夹回
//
// "自动结束当前段" 由 SwiftUI 的 Timer 驱动 — 时间到 endsAt 就调 advance()

@MainActor
@Observable
final class TrainingSessionStore {
    /// "做完了一组" 的 key — 用 (stepId, setN) 而非 segmentIndex,
    /// 让 step 参数被编辑后, 已完成状态依然保留 (segment 重新生成 index 会变, stepId+setN 不变).
    struct CompletedSet: Hashable, Sendable {
        let stepId: String
        let setN: Int
    }

    struct Session: Hashable {
        let planId: String
        var segmentIndex: Int = 0
        var playing: Bool = true
        /// 倒计时目标时刻 (timeIntervalSinceReferenceDate); nil 表示等用户点完成或暂停
        var endsAt: Date?
        var pausedRemaining: TimeInterval?
        let startedAt: Date
        /// 训练已走完最后一段, 等用户确认结束
        var completed: Bool = false
        /// 最后一次用户交互 (advance / setIndex / togglePlay) 的时间
        /// 用于 6h-inactive auto-complete: 用户关机走了 / 忘了, 不能让训练永远挂着
        var lastActiveAt: Date = .init()
        /// 用户主动点"打勾"完成的组集合 — 只有 advance() (而非 setIndex 跳过) 才会写入.
        /// playlist + TimelineBar 用这个判断"哪些段真的做完了, 该标绿". 跳过的段保持灰.
        var completedSets: Set<CompletedSet> = []
    }

    private(set) var session: Session?
    /// 用户主动结束的标记 — 防止 player view 的 onAppear 又 auto-restart
    var endedExplicitly: Bool = false

    /// 1Hz tick probe — 让 `remainingSeconds` 这类基于 `Date()` 的 computed property
    /// 通过 Observation 建立"我依赖 tickProbe"的图谱. SessionTickerView 每 0.5s 改一次,
    /// 所有读 remainingSeconds 的 view (MiniBar / Player) 自动重算.
    ///
    /// 没这个的话, remainingSeconds 内部用 `Date()` 是非 observed 的, view 不会自己刷新.
    /// (PlanPlayer 之前能动是因为它 onAppear 时频繁状态变化, 但 sheet 收起后 MiniBar 只在
    /// session.endsAt / segmentIndex 改变时才刷新, 中间几十秒倒计时就定住了.)
    var tickProbe: UInt32 = 0

    /// 这两个是从 DataStore 衍生出来的 — UI 层从外部传入
    var plan: Plan?
    var segments: [Segment] = []

    /// 训练中是否修改过 plan 参数 (sets/reps/weight/duration/顺序). 结束时如果 dirty 且
    /// plan 不是自由训练 (autoGenerated), 弹"保存到训练计划?"提示让用户决定是否持久化.
    /// start() 时重置 false; updateCurrentStep / reorderSteps 末尾设 true.
    private(set) var planParamsDirty: Bool = false

    /// 当前段 (索引夹紧后)
    var currentSegment: Segment? {
        guard !segments.isEmpty, let s = session else { return nil }
        let i = min(max(0, s.segmentIndex), segments.count - 1)
        return segments[i]
    }

    /// 当前段计算的剩余秒数 (nil = 没在倒计时)
    var remainingSeconds: Int? {
        // 建立 Observation 依赖: tickProbe 每 0.5s 被 SessionTickerView 改一次,
        // 强制所有读 remainingSeconds 的 view 跟着重算. 不能去掉这一行.
        _ = tickProbe
        guard let s = session else { return nil }
        if !s.playing, let p = s.pausedRemaining { return Int(ceil(p)) }
        guard let endsAt = s.endsAt else { return nil }
        let rem = endsAt.timeIntervalSinceNow
        return max(0, Int(ceil(rem)))
    }

    /// 训练超过 N 小时无交互 → 自动判定完成 (避免用户关机后还挂着上一天的训练)
    static let autoCompleteAfter: TimeInterval = 6 * 60 * 60  // 6h

    func start(planId: String, plan: Plan?, segments: [Segment]) {
        endedExplicitly = false
        self.plan = plan
        self.segments = segments
        self.planParamsDirty = false  // 新一次训练 — 重置改动标志
        let seg = segments.first
        let endsAt = initialEndsAt(for: seg)
        session = Session(
            planId: planId,
            segmentIndex: 0,
            playing: true,
            endsAt: endsAt,
            pausedRemaining: nil,
            startedAt: Date(),
            completed: false,
            lastActiveAt: Date()
        )
        // 启动 Live Activity — 锁屏 / Dynamic Island 训练状态小窗
        LiveActivityManager.shared.start(
            planName: plan?.name ?? NSLocalizedString("Workout", comment: ""),
            initialState: liveActivityState(for: seg, endsAt: endsAt)
        )
        // Watch 镜像 — 新训练重置 HK 防双计标记, 推开局帧
        WatchSyncManager.shared.resetForNewWorkout()
        syncWatch()
    }

    /// 把当前 segment + endsAt 翻译成 Live Activity 的 ContentState
    private func liveActivityState(
        for segment: Segment?,
        endsAt: Date?
    ) -> TrainingActivityAttributes.ContentState {
        guard let segment else {
            return TrainingActivityAttributes.ContentState(segmentLabel: "—", setProgress: "")
        }
        switch segment.kind {
        case .rest:
            return TrainingActivityAttributes.ContentState(
                segmentLabel: NSLocalizedString("Rest", comment: ""),
                setProgress: "",
                endsAt: endsAt,
                isRest: true,
                nextExerciseName: nextExerciseName(after: segment)
            )
        case .exercise(let ex, let setN, let total, _, _, _, let countdown):
            return TrainingActivityAttributes.ContentState(
                segmentLabel: ex.displayName,
                setProgress: "\(setN)/\(total)",
                endsAt: countdown ? endsAt : nil,
                isRest: false,
                nextExerciseName: nil
            )
        }
    }

    /// rest 段时, 找下一个 exercise 名 — 用在 Live Activity "Next: XX" 提示
    private func nextExerciseName(after current: Segment) -> String? {
        guard let s = session, let i = segments.firstIndex(where: { $0.id == current.id }) else { return nil }
        for j in (i + 1)..<segments.count {
            if case .exercise(let ex, _, _, _, _, _, _) = segments[j].kind {
                return ex.displayName
            }
        }
        _ = s
        return nil
    }

    /// 同步当前 state 到 Live Activity. 在所有 session mutating 函数末尾调.
    private func syncLiveActivity() {
        guard let s = session else { return }
        let seg = currentSegment
        LiveActivityManager.shared.update(
            liveActivityState(for: seg, endsAt: s.endsAt)
        )
        syncWatch()
    }

    /// 标记"用户仍在主动用" — bump lastActiveAt, 避免活跃 session 被 6h idle 误判完成.
    /// P2-9: 之前只有 advance/setIndex/togglePlay/编辑 算活动; 拖 playlist、进播放页这种
    /// 也算用户在场. 只在前台被调 (onAppear / 拖拽 onEnded), 不会重置"后台放置"的计时.
    func noteActivity() {
        guard var s = session, !s.completed else { return }
        s.lastActiveAt = Date()
        session = s
    }

    /// 检查 idle 时长, 超过 6h 自动 mark completed
    /// SessionTickerView 每 0.5s 调一次; app 从后台 resume 时也调
    func checkAutoComplete() {
        guard var s = session, !s.completed else { return }
        let idle = Date().timeIntervalSince(s.lastActiveAt)
        guard idle >= Self.autoCompleteAfter else { return }
        // 6h+ 没动 — 当作完成
        s.completed = true
        s.playing = false
        s.endsAt = nil
        session = s
        LiveActivityManager.shared.end()
        syncWatch()
    }

    func setIndex(_ i: Int) {
        guard var s = session else { return }
        let safe = min(max(0, i), max(0, segments.count - 1))
        s.segmentIndex = safe
        let seg = segments[safe]
        // P2-8: 保留暂停态 — 之前无条件 playing=true, 暂停的用户点 playlist 跳一下就被静默恢复.
        // 暂停中跳转: 计时段把满时长存 pausedRemaining (恢复时从该段起算), 不自动跑.
        if s.playing {
            s.endsAt = initialEndsAt(for: seg)
            s.pausedRemaining = nil
        } else {
            s.endsAt = nil
            s.pausedRemaining = initialPausedRemaining(for: seg)
        }
        s.lastActiveAt = Date()  // 用户交互 — reset idle
        session = s
        syncLiveActivity()
    }

    func togglePlay() {
        guard var s = session else { return }
        if s.playing {
            if let endsAt = s.endsAt {
                s.pausedRemaining = max(0, endsAt.timeIntervalSinceNow)
                s.endsAt = nil
            }
            s.playing = false
        } else {
            if let p = s.pausedRemaining {
                s.endsAt = Date().addingTimeInterval(p)
                s.pausedRemaining = nil
            }
            s.playing = true
        }
        s.lastActiveAt = Date()  // 用户交互 — reset idle
        session = s
        syncLiveActivity()
    }

    func advance(record: ((SetRecord) -> Void)? = nil) {
        guard var s = session else { return }
        let curWasRest = currentSegment?.isRest ?? false
        // "完成组" 触觉 + 上行 chime — 适用于 manual-confirm 类型的组
        // (打勾按钮: strength + flexibility). cardio 自动倒计时不算 — 倒计时结束已有
        // restEnded 的反馈, 不再二次提示.
        let curWasStrength: Bool = {
            if case .exercise(let ex, _, _, _, _, _, let countdown) = currentSegment?.kind {
                return !countdown && (ex.category == .strength || ex.category == .flexibility)
            }
            return false
        }()
        // 保存力量段的训练记录 + 标记 (stepId, setN) 已完成
        // —— advance() 是"用户点打勾 / 倒计时自然走完", 是真完成. setIndex 不走这里.
        if let cur = currentSegment, case .exercise(let ex, let setN, _, let reps, let weight, let dur, _) = cur.kind {
            let rec = SetRecord(
                id: UUID().uuidString,
                exerciseId: ex.id,
                exerciseName: ex.name,
                category: ex.category,
                weight: weight,
                reps: reps,
                duration: dur,
                performedAt: Date(),
                planId: s.planId
            )
            record?(rec)
            // 写入"已做完"集合 — playlist / TimelineBar 据此标绿
            s.completedSets.insert(CompletedSet(stepId: cur.stepId, setN: setN))
        }
        let next = s.segmentIndex + 1
        if next >= segments.count {
            s.completed = true
            s.playing = false
            s.endsAt = nil
            session = s
            Haptics.trainingComplete() // DESIGN 7: 训练完成触觉
            LiveActivityManager.shared.end()
            syncWatch()
            return
        }
        s.segmentIndex = next
        let seg = segments[next]
        s.endsAt = initialEndsAt(for: seg)
        s.pausedRemaining = nil
        s.playing = true
        s.lastActiveAt = Date()  // advance 也算用户活动
        session = s
        syncLiveActivity()
        // DESIGN 7: 关键节点触觉 + 音效反馈 (都跟用户的音乐共存, 不打断).
        if curWasRest {
            Haptics.restEnded()
            // 休息结束 (无论自动倒计时归零 or 用户手动 skip) — 都放一次上行音
            SoundPlayer.shared.playRestEnded()
        } else if curWasStrength {
            Haptics.setComplete()
            SoundPlayer.shared.playSetComplete()
        }
        // 新段是 rest → 进入休息提示 (轻下行音 E5→C5), 不管前一段是什么.
        // 跟 setComplete 不冲突: 完成组 chime → 立刻进 rest → enterRest 接着响,
        // 两个音都是短的 (~200ms), 衔接自然.
        if seg.isRest {
            SoundPlayer.shared.playEnterRest()
        }
    }

    func end() {
        session = nil
        plan = nil
        segments = []
        LiveActivityManager.shared.end()
        syncWatch()   // → idle
    }

    /// 提前结束 — 跳到 completed 态保留已完成组. 跟 end() 区别: end 清空 session (=放弃),
    /// finishEarly 把它标记完成 (=用户主动提前圆满收工, CompletedView 会显示).
    func finishEarly() {
        guard var s = session else { return }
        s.completed = true
        s.playing = false
        s.endsAt = nil
        s.lastActiveAt = Date()
        session = s
        Haptics.trainingComplete()
        LiveActivityManager.shared.end()
        syncWatch()
    }

    /// "上一段" — 跳过休息直接回到上一个动作
    func skipBackToPrevExercise() {
        guard let s = session else { return }
        let cur = s.segmentIndex
        var i = cur - 1
        while i >= 0 {
            if !segments[i].isRest {
                setIndex(i)
                return
            }
            i -= 1
        }
        // 没有更早的 exercise — 留在原地
    }

    var canSkipBack: Bool {
        guard let s = session else { return false }
        var i = s.segmentIndex - 1
        while i >= 0 {
            if !segments[i].isRest { return true }
            i -= 1
        }
        return false
    }

    private func initialEndsAt(for seg: Segment?) -> Date? {
        guard let seg else { return nil }
        switch seg.kind {
        case .rest(let dur):
            return Date().addingTimeInterval(TimeInterval(dur))
        case .exercise(_, _, _, _, _, let dur, let countdown):
            if countdown, let dur, dur > 0 {
                return Date().addingTimeInterval(TimeInterval(dur))
            }
            return nil // 力量动作: 等用户点完成
        }
    }

    /// 该段满时长 (秒) — 暂停态跳转时用, 存进 pausedRemaining 让恢复时从满时长起算.
    /// nil = 该段不计时 (力量动作).
    private func initialPausedRemaining(for seg: Segment?) -> TimeInterval? {
        guard let seg else { return nil }
        switch seg.kind {
        case .rest(let dur):
            return TimeInterval(dur)
        case .exercise(_, _, _, _, _, let dur, let countdown):
            if countdown, let dur, dur > 0 { return TimeInterval(dur) }
            return nil
        }
    }

    // MARK: - 训练中编辑当前 step 参数 (组数 / 次数 / 重量 / 时长)

    /// 训练中编辑当前动作的参数. 全字段 mandatory — UI 端始终带当前值, 用户保存时写回所有 4 个字段.
    /// 不改 = UI 端把现值传回来. 清空 = UI 端把 nil 传回来 (比如清空 reps).
    ///
    /// 工作流:
    ///   1. 改 self.plan.steps[i] 的字段 (session-local, 不写回 DataStore)
    ///   2. 重新 expandPlan 生成新 segments — sets 改了会增删 segments
    ///   3. 把 segmentIndex 映射到新 segments 中相同 (stepId, setN) 的位置
    ///   4. completedSets 用 (stepId, setN) key, 重新生成后自动保留
    ///   5. 重置 endsAt — 改了 duration/reps 后, 旧倒计时目标不一定对, 简单重新计
    ///
    /// 边界:
    ///   - 新 sets < 当前 setN → 当前 set 已超出 → 跳到下一 step 第一个 exercise (没下一 step 则训练完成)
    ///   - 当前在 rest → 跳到该 step 中"尚未完成"的下一个 exercise; 都完成了跳下一 step
    /// 训练中编辑任意 step 参数 (不只是当前) — InlinePlaylist 右滑 Edit 用.
    /// 跟 updateCurrentStep 同 session-local 逻辑, 只是 base step 由参数指定不是 currentSegment.
    /// 当前在做的 segment 跟着原 stepId+setN 在新 segments 里 re-find 位置.
    func updateStep(
        _ stepId: String,
        sets newSets: Int,
        reps newReps: Int?,
        weight newWeight: Double?,
        duration newDuration: Int?,
        setReps newSetReps: [Int?]? = nil,
        setWeights newSetWeights: [Double?]? = nil,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan else { return }
        guard let stepIdx = p.steps.firstIndex(where: { $0.id == stepId }) else { return }

        // 捕获当前位置 — 用户编辑别的 step 时, 当前 segment 位置可能因 sets 变化重排
        let curStepId = currentSegment?.stepId
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = currentSegment?.kind {
            curSetN = sn
        }
        let wasRest = currentSegment?.isRest ?? false

        // 改 plan
        var step = p.steps[stepIdx]
        step.sets = max(1, newSets)
        step.reps = newReps
        step.weight = newWeight
        step.setReps = newSetReps
        step.setWeights = newSetWeights
        step.duration = newDuration
        p.steps[stepIdx] = step
        self.plan = p

        // 重新 expand
        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        // 映射当前 segmentIndex
        var newIdx: Int? = nil
        if let cstpid = curStepId, let csn = curSetN {
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == cstpid,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == csn { return true }
                return false
            })
        } else if let cstpid = curStepId, wasRest {
            newIdx = newSegments.firstIndex(where: { $0.stepId == cstpid && $0.isRest })
        }

        s.segmentIndex = min(max(0, newIdx ?? 0), max(0, newSegments.count - 1))
        // P0-4: 如果编辑的就是当前 step (改了 duration / countdown 类别), 重算计时器 —
        // 否则当前有氧段会沿用旧 endsAt, 显示的 duration 跟实际倒计时不符.
        if stepId == curStepId {
            let seg = newSegments[s.segmentIndex]
            s.endsAt = initialEndsAt(for: seg)
            s.pausedRemaining = nil
        }
        s.lastActiveAt = Date()
        session = s
        planParamsDirty = true
        syncLiveActivity()
    }

    /// 训练中替换一个 step 的 exercise (sets/reps/weight/duration 全保留).
    /// "动作换, 强度不变" — 跟 PlansScreen 的右滑 Replace 同语义, 区别只在这里是 session-local
    /// (改 self.plan / segments). 结束时 planParamsDirty=true 触发"保存替换到 plan?"提示.
    ///
    /// 当前 segment 跟着 stepId+setN 在重 expand 后的 segments 里 re-find 位置, 用户不会跳段.
    func replaceStepExercise(
        _ stepId: String,
        newExerciseId: String,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan else { return }
        guard let stepIdx = p.steps.firstIndex(where: { $0.id == stepId }) else { return }

        // 捕当前位置 — 跟 updateStep 同套路
        let curStepId = currentSegment?.stepId
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = currentSegment?.kind {
            curSetN = sn
        }
        let wasRest = currentSegment?.isRest ?? false

        // 替 exerciseId — PlanStep.exerciseId 是 let, 用整 step 重建保留其它字段.
        let old = p.steps[stepIdx]
        p.steps[stepIdx] = PlanStep(
            id: old.id,
            exerciseId: newExerciseId,
            sets: old.sets,
            reps: old.reps,
            weight: old.weight,
            duration: old.duration,
            restBetweenSets: old.restBetweenSets,
            rest: old.rest
        )
        self.plan = p

        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        // 映射当前 segmentIndex 回去
        var newIdx: Int? = nil
        if let cstpid = curStepId, let csn = curSetN {
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == cstpid,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == csn { return true }
                return false
            })
        } else if let cstpid = curStepId, wasRest {
            newIdx = newSegments.firstIndex(where: { $0.stepId == cstpid && $0.isRest })
        }
        s.segmentIndex = min(max(0, newIdx ?? 0), max(0, newSegments.count - 1))
        // P0-4: 替换的是当前 step 时, 新动作的 countdown 类别可能跟旧的不同 (力量↔有氧),
        // 必须重算计时器 — 否则力量→有氧卡 0:00 无法前进, 有氧→力量会被旧 endsAt 自动记一组.
        if stepId == curStepId {
            let seg = newSegments[s.segmentIndex]
            s.endsAt = initialEndsAt(for: seg)
            s.pausedRemaining = nil
        }
        s.lastActiveAt = Date()
        session = s
        planParamsDirty = true
        syncLiveActivity()
    }

    func updateCurrentStep(
        sets newSets: Int,
        reps newReps: Int?,
        weight newWeight: Double?,
        duration newDuration: Int?,
        setReps newSetReps: [Int?]? = nil,
        setWeights newSetWeights: [Double?]? = nil,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan, let cur = currentSegment else { return }
        let stepId = cur.stepId
        guard let stepIdx = p.steps.firstIndex(where: { $0.id == stepId }) else { return }

        // 捕获当前位置信息 — 重新展开后用来定位新 index
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = cur.kind {
            curSetN = sn
        }
        let wasRest = cur.isRest

        // 改 plan 数据 (session-local copy)
        var step = p.steps[stepIdx]
        step.sets = max(1, newSets)
        step.reps = newReps
        step.weight = newWeight
        step.setReps = newSetReps
        step.setWeights = newSetWeights
        step.duration = newDuration
        p.steps[stepIdx] = step
        self.plan = p

        // 重新展开
        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        // 映射 segmentIndex
        var newIdx: Int? = nil
        if let sn = curSetN {
            // 当前在 exercise — 优先找 (stepId, sn). 找不到 (sets 减到 < sn) → 下一 step.
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == stepId,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == sn { return true }
                return false
            }) ?? nextStepExerciseIndex(in: newSegments, plan: p, afterStepId: stepId)
        } else if wasRest {
            // 当前在 rest — 找该 step 内"尚未完成"的下一 exercise
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == stepId,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   !s.completedSets.contains(CompletedSet(stepId: stepId, setN: n)) {
                    return true
                }
                return false
            }) ?? nextStepExerciseIndex(in: newSegments, plan: p, afterStepId: stepId)
        }

        guard let resolved = newIdx else {
            // 无处可去 — 训练完成 (用户把 sets 改到很小, 之前的 set 都做完了)
            s.completed = true
            s.playing = false
            s.endsAt = nil
            session = s
            Haptics.trainingComplete()
            LiveActivityManager.shared.end()
            syncWatch()
            return
        }

        s.segmentIndex = min(max(0, resolved), max(0, newSegments.count - 1))
        let seg = newSegments[s.segmentIndex]
        s.endsAt = initialEndsAt(for: seg)
        s.pausedRemaining = nil
        s.playing = true
        s.lastActiveAt = Date()
        session = s
        planParamsDirty = true  // 改了参数 — 结束时提示保存
        syncLiveActivity()
    }

    /// 训练中拖拽排序 plan.steps. 跟 updateCurrentStep 一样, 全程 session-local — 改 self.plan
    /// + 重新 expandPlan + 定位新 segmentIndex, 不写回 DataStore.plans.
    ///
    /// 行为:
    ///   - completedSets 用 (stepId, setN) key, 不受顺序影响, 自动保留
    ///   - 当前 step 跟着位置走 (用户在做 chest press, 拖到 plan 第一 → chest press 仍是当前)
    ///   - segmentIndex 映射到 (curStepId, curSetN) 在新 segments 里的新位置
    ///   - endsAt / pausedRemaining 都保留 — 拖排序不打断计时
    ///
    /// 用户长期想保存这个顺序 → 走 Plan 编辑器 (跟 updateCurrentStep 一致, 训练中改的都不持久).
    func reorderSteps(
        from source: IndexSet,
        to destination: Int,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan, let cur = currentSegment else { return }
        let curStepId = cur.stepId
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = cur.kind {
            curSetN = sn
        }
        let wasRest = cur.isRest

        // 移动 — SwiftUI ForEach.onMove 的语义跟 Array.move(fromOffsets:toOffset:) 一致
        p.steps.move(fromOffsets: source, toOffset: destination)
        self.plan = p

        // 重新展开 segments. completedSets 是按 (stepId, setN) 索引, 不依赖顺序.
        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        // 把 segmentIndex 重新映射到当前 (stepId, setN) 在新 segments 中的位置.
        var newIdx: Int? = nil
        if let sn = curSetN {
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == curStepId,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == sn { return true }
                return false
            })
        } else if wasRest {
            // 当前在 rest 段 — 找当前 step 的 rest segment (同 stepId + isRest).
            newIdx = newSegments.firstIndex(where: { $0.stepId == curStepId && $0.isRest })
        }

        guard let resolved = newIdx else {
            // 不应发生 (move 不会让 curStepId 消失) — 兜底回 0.
            s.segmentIndex = 0
            session = s
            syncLiveActivity()
            return
        }

        s.segmentIndex = min(max(0, resolved), max(0, newSegments.count - 1))
        s.lastActiveAt = Date()
        session = s
        planParamsDirty = true  // 改了顺序 — 结束时提示保存
        syncLiveActivity()
    }

    /// 训练中删除一个 step (session-local, 不写回 DataStore.plans).
    /// 跟 reorderSteps / updateCurrentStep 同模式: 改 self.plan + 重新 expandPlan + 定位新 segmentIndex.
    ///
    /// 边界处理:
    ///   - 删的是当前 step → 跳到下一个未完成 exercise (没有则训练完成)
    ///   - 删的是其它 step → 当前 (stepId, setN) 在新 segments 里找到新位置
    ///   - 该 step 的 completedSets 一并清掉 (避免孤儿数据)
    ///   - plan 删空 → 训练完成
    /// 训练中追加一个新动作 — 自由训练 / 中途想加一个的入口. 跟 ExercisePickerSheet 同 onPick
    /// 语义: 选完一个 exercise, 用合理 defaults 构造 PlanStep, 加到 plan.steps 末尾, 重 expand.
    /// 当前 segment 跟着 stepId+setN 在新 segments 里 re-find, 用户不会跳段.
    ///
    /// reps / sets 默认值走用户 Training Preferences (settings.trainingGoal + defaultSetsPerExercise),
    /// 而非硬编码 3 sets × 10 reps. 让"中途加一个动作"也尊重用户设的训练目标.
    func appendStep(
        exercise: Exercise,
        settings: UserSettings,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan else { return }

        // 捕当前位置 — 跟 updateStep / replaceStepExercise 同模式.
        let curStepId = currentSegment?.stepId
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = currentSegment?.kind {
            curSetN = sn
        }
        let wasRest = currentSegment?.isRest ?? false

        // Defaults 从 Training Preferences 推导:
        //   - sets = settings.defaultSetsPerExercise
        //   - reps (力量动作) = goal × mechanic (compound vs isolation)
        //   - rest = settings.defaultRestSeconds (用户调过) 否则 goal 推荐值
        let isCompound = exercise.mechanic == .compound
        let reps: Int? = exercise.category == .strength
            ? (isCompound
               ? settings.trainingGoal.defaultRepsForCompound()
               : settings.trainingGoal.defaultRepsForIsolation())
            : nil
        let newStep = PlanStep(
            id: "step-\(exercise.id)-\(Int(Date().timeIntervalSince1970))",
            exerciseId: exercise.id,
            sets: settings.defaultSetsPerExercise,
            reps: reps,
            weight: exercise.category == .strength ? 0 : nil,
            duration: exercise.category != .strength ? 30 : nil,
            restBetweenSets: settings.defaultRestSeconds,
            rest: 0
        )
        p.steps.append(newStep)
        self.plan = p

        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        // 映射当前 segmentIndex 回去
        var newIdx: Int? = nil
        if let cstpid = curStepId, let csn = curSetN {
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == cstpid,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == csn { return true }
                return false
            })
        } else if let cstpid = curStepId, wasRest {
            newIdx = newSegments.firstIndex(where: { $0.stepId == cstpid && $0.isRest })
        }
        s.segmentIndex = min(max(0, newIdx ?? 0), max(0, newSegments.count - 1))
        s.lastActiveAt = Date()
        session = s
        planParamsDirty = true
        syncLiveActivity()
    }

    func deleteStep(
        _ stepId: String,
        exById: [String: Exercise],
        defaultRest: Int,
        defaultBetweenExerciseRest: Int
    ) {
        guard var s = session, var p = plan else { return }
        // 删之前捕获当前位置, 用于映射
        let curStepId = currentSegment?.stepId
        let oldSegIdx = s.segmentIndex  // P2-7: 删当前 step 时从这个位置向后找, 不从 0 倒回
        var curSetN: Int? = nil
        if case .exercise(_, let sn, _, _, _, _, _) = currentSegment?.kind {
            curSetN = sn
        }

        // 移除 step + 清掉该 step 的 completedSets (孤儿数据)
        p.steps.removeAll { $0.id == stepId }
        s.completedSets = s.completedSets.filter { $0.stepId != stepId }

        self.plan = p

        // plan 删空 → 训练完成
        if p.steps.isEmpty {
            s.completed = true
            s.playing = false
            s.endsAt = nil
            session = s
            segments = []
            planParamsDirty = true
            LiveActivityManager.shared.end()
            syncWatch()
            return
        }

        // 重新 expand segments + 定位 segmentIndex
        let newSegments = expandPlan(
            p,
            exById: exById,
            defaultRest: defaultRest,
            defaultBetweenExerciseRest: defaultBetweenExerciseRest
        )
        self.segments = newSegments

        var newIdx: Int? = nil
        if curStepId == stepId {
            // P2-7: 删的是当前 step — 从删除位置 *向后* 找第一个未完成 exercise (不从 0 倒回,
            // 否则会把用户甩回更早跳过的 step). 向后没有了再 fallback 全局找 / 0.
            let anchor = min(max(0, oldSegIdx), max(0, newSegments.count - 1))
            func firstUncompleted(from start: Int) -> Int? {
                guard start < newSegments.count else { return nil }
                for k in start..<newSegments.count {
                    guard case .exercise(_, let sn, _, _, _, _, _) = newSegments[k].kind else { continue }
                    if !s.completedSets.contains(CompletedSet(stepId: newSegments[k].stepId, setN: sn)) {
                        return k
                    }
                }
                return nil
            }
            newIdx = firstUncompleted(from: anchor) ?? firstUncompleted(from: 0) ?? 0
        } else if let stp = curStepId, let sn = curSetN {
            // 删的是其它 step — 当前位置可能 index 变了, 重新找
            newIdx = newSegments.firstIndex(where: {
                if $0.stepId == stp,
                   case .exercise(_, let n, _, _, _, _, _) = $0.kind,
                   n == sn { return true }
                return false
            })
        }

        s.segmentIndex = min(max(0, newIdx ?? 0), max(0, newSegments.count - 1))
        s.lastActiveAt = Date()
        // 进入新 segment, 重置计时
        let seg = newSegments[s.segmentIndex]
        s.endsAt = initialEndsAt(for: seg)
        s.pausedRemaining = nil
        session = s
        planParamsDirty = true  // 改了 plan — 结束时提示保存
        syncLiveActivity()
    }

    // MARK: - Watch 镜像 (#apple-watch)

    /// 把当前 session 翻译成手表的一帧状态. session nil → idle; completed → done.
    private func makeWatchState() -> WatchSyncState {
        guard let s = session else { return .idle }
        var st = WatchSyncState()
        st.planName = plan?.name ?? ""
        st.totalSets = segments.filter(\.isExercise).count
        st.doneSets = s.completedSets.count
        if s.completed {
            st.mode = .done
            return st
        }
        guard let seg = currentSegment else { return .idle }
        st.paused = !s.playing
        st.endsAt = s.playing ? s.endsAt : nil
        st.pausedRemaining = s.pausedRemaining.map { Int(ceil($0)) }
        switch seg.kind {
        case .rest:
            st.mode = .rest
            st.nextExercise = nextExerciseName(after: seg)
        case .exercise(let ex, let setN, let total, let reps, let weight, let dur, let countdown):
            st.mode = .exercise
            st.exerciseName = ex.displayName
            st.setN = setN
            st.setTotal = total
            st.manualConfirm = !countdown
            var parts: [String] = []
            if let reps {
                parts.append(String(format: NSLocalizedString("%d reps", comment: "watch detail"), reps))
            }
            if let weight, weight > 0 {
                let num = weight.truncatingRemainder(dividingBy: 1) == 0
                    ? String(format: "%.0f", weight) : String(format: "%.1f", weight)
                parts.append("\(num) kg")
            }
            if countdown, let dur, dur > 0 {
                parts.append(String(format: "%d:%02d", dur / 60, dur % 60))
            }
            st.detail = parts.joined(separator: " · ")
        }
        return st
    }

    private func syncWatch() {
        WatchSyncManager.shared.sync(makeWatchState())
    }

    /// App 启动时推一帧当前状态 — 不然手机被杀后重启, 手表会永远停在上一次训练的旧帧
    /// (没有 mutation 就没有 sync). MasoApp .task 调.
    func pushWatchState() { syncWatch() }

    /// 找指定 stepId 之后的下一 step 的第一个 exercise segment index. 没有 → nil.
    private func nextStepExerciseIndex(in segs: [Segment], plan: Plan, afterStepId stepId: String) -> Int? {
        guard let curStepIdx = plan.steps.firstIndex(where: { $0.id == stepId }),
              curStepIdx + 1 < plan.steps.count else { return nil }
        let nextStepId = plan.steps[curStepIdx + 1].id
        return segs.firstIndex(where: { $0.stepId == nextStepId && $0.isExercise })
    }
}

// MARK: - 1Hz 计时器, 驱动 endsAt → 自动 advance + 倒计时刷新

struct SessionTickerView: View {
    @Environment(TrainingSessionStore.self) private var store
    @Environment(DataStore.self) private var data
    @State private var tick = 0

    var body: some View {
        Color.clear
            .onReceive(Timer.publish(every: 0.5, on: .main, in: .common).autoconnect()) { _ in
                // 1) 6h idle auto-complete
                store.checkAutoComplete()
                // 2) endsAt 到点自动 advance
                guard let s = store.session, s.playing, let endsAt = s.endsAt else { return }
                if endsAt <= Date() {
                    store.advance { rec in data.recordSet(rec) }
                } else {
                    // 改 store 上的 observed property — 所有读 remainingSeconds 的 view 都会重算.
                    // (之前用 SessionTickerView 内部 @State tick 只让 ticker 自己刷新, 没用.)
                    store.tickProbe &+= 1
                    tick &+= 1
                }
            }
            .onReceive(NotificationCenter.default.publisher(for: UIApplication.willEnterForegroundNotification)) { _ in
                // app 从后台回前台立即检查一次 (用户可能关屏 8h 后再开)
                store.checkAutoComplete()
            }
            .allowsHitTesting(false)
    }
}
