import Foundation

// PlanShareCodec — Plan ↔ base64 URL safe string, 用于 maso:// deep link 分享.
//
// 流程:
//   - 分享方: 在 PlanDetailSheet 点 Share → encode(plan) 得到 base64 字符串
//     → shareURL(for:) 拼成 maso://import?plan=<base64> → UIActivityViewController
//     → 用户选 Messages/AirDrop/Copy → 接收方点开链接.
//   - 接收方: MasoApp.onOpenURL 拦到 maso:// → 取 query "plan" → decode → 弹 ImportedPlanSheet
//     → 用户 Add → 进 data.plans.
//
// 编码尽量小:
//   - JSONEncoder, 默认无 prettyPrint, key 顺序稳定 (sortedKeys 关掉, 节省字节).
//   - 不删字段 (Plan 字段本来就少, 30-40 字节/字段; 强删 lastUsedAt 之类省不到 50 字节, 不值得引入二级 DTO).
//   - 用 base64url (RFC 4648 §5) 替换 '+', '/', '='. URL 直接可放, 不用 percent-encode.
//
// 大小估计 (典型 8 动作 plan):
//   - JSON ~600B, base64 ~800B. 装得下 URL (典型上限 2KB).
//   - 上限 ~25 动作前都安全 (≈2.5KB base64).
//
// 错误兜底:
//   - encode 失败 → nil (调用方应当 fallback 到 alert).
//   - decode 严格: base64 invalid / JSON invalid / 缺字段 → nil.
//   - 新 id 用 "plan-shared-" prefix + UUID 后缀, 避免跟原作者 plan id 冲突.
//   - autoGenerated 强制设 false (分享的 plan 是"用户的", 不是系统推荐).
//   - lastUsedAt 重置 (接收方还没练过).
enum PlanShareCodec {

    /// URL scheme + host. 改这两个 → 同步改 project.yml 的 CFBundleURLSchemes.
    static let urlScheme = "maso"
    static let urlHost = "import"
    static let urlQueryKey = "plan"

    /// 编码: Plan → base64url string. 编码失败返 nil (理论上 Codable Plan 不会失败,
    /// 但保留 nil 出口让调用方稳健).
    static func encode(_ plan: Plan) -> String? {
        let encoder = JSONEncoder()
        // ISO8601 字符串比默认 .secondsSince1970 多几个字节但语义清楚 (跨版本兼容更稳).
        // Plan 里就 2 个 Date 字段 (createdAt, updatedAt), 加 lastUsedAt 共 3 个, 多花 ~60B 可接受.
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(plan) else { return nil }
        return data.base64URLEncodedString()
    }

    /// 解码: base64url → Plan. 给新 id (prefix "plan-shared-") 防跟原作者冲突.
    /// 任何步骤失败返 nil — 调用方应当 alert "invalid link".
    static func decode(_ encoded: String) -> Plan? {
        guard let data = Data(base64URLEncoded: encoded) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard var plan = try? decoder.decode(Plan.self, from: data) else { return nil }
        // 给新 id 防冲突 (导入的 plan ≠ 原作者 plan, 即使两人 id 撞了也分得开)
        let now = Date()
        let newId = "plan-shared-\(Int(now.timeIntervalSince1970))-\(UUID().uuidString.prefix(6))"
        plan = Plan(
            id: newId,
            name: plan.name,
            steps: plan.steps,
            createdAt: now,         // 接收方"添加"的时间, 不是原作者建 plan 的时间
            updatedAt: now,
            autoGenerated: false,   // 分享的 plan 一律算用户创建的
            lastUsedAt: nil         // 接收方还没练
        )
        return plan
    }

    /// 生成可分享 URL: e.g. maso://import?plan=eyJpZCI6...
    /// 失败返 nil (encode 失败).
    static func shareURL(for plan: Plan) -> URL? {
        guard let encoded = encode(plan) else { return nil }
        var comps = URLComponents()
        comps.scheme = urlScheme
        comps.host = urlHost
        comps.queryItems = [URLQueryItem(name: urlQueryKey, value: encoded)]
        return comps.url
    }

    /// 拦截 onOpenURL — 校验 scheme/host, 取 query "plan", 解码 → Plan.
    /// 返 nil 时调用方应当忽略 (可能是别的 deep link, 或损坏链接).
    static func decodePlan(from url: URL) -> Plan? {
        guard url.scheme == urlScheme else { return nil }
        guard url.host == urlHost else { return nil }
        guard let comps = URLComponents(url: url, resolvingAgainstBaseURL: false) else { return nil }
        guard let encoded = comps.queryItems?.first(where: { $0.name == urlQueryKey })?.value else { return nil }
        return decode(encoded)
    }
}

// MARK: - base64url helpers
//
// RFC 4648 §5: 标准 base64 的 '+' '/' '=' 在 URL 里有特殊含义, 改成 '-' '_' 并去掉 padding '='.
// URLComponents 会帮忙 percent-encode, 但用 base64url 让 URL 字符串本身就干净 (用户复制粘贴友好).

private extension Data {
    func base64URLEncodedString() -> String {
        return self.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    init?(base64URLEncoded string: String) {
        var s = string
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        // 补 padding 到 4 的倍数 (base64 要求)
        let padLen = (4 - s.count % 4) % 4
        s.append(String(repeating: "=", count: padLen))
        self.init(base64Encoded: s)
    }
}
