import Foundation

// PlanShareCodec — Plan ↔ base64 URL safe string, 用于 maso:// deep link 分享.
//
// 流程:
//   - 分享方: 在 PlanDetailSheet 点 Share → encode(plan) 得到 base64 字符串
//     → shareURL(for:) 拼成 maso://import?plan=<base64> → UIActivityViewController
//     → 用户选 Messages/AirDrop/Copy → 接收方点开链接.
//   - 接收方: MasoApp.onOpenURL 拦到 maso:// → 取 query "plan" → decode → 弹 ImportedPlanSheet
//     → 用户 Add → 进 data.plans.
//
// 编码尽量小:
//   - JSONEncoder, 默认无 prettyPrint, key 顺序稳定 (sortedKeys 关掉, 节省字节).
//   - 不删字段 (Plan 字段本来就少, 30-40 字节/字段; 强删 lastUsedAt 之类省不到 50 字节, 不值得引入二级 DTO).
//   - 用 base64url (RFC 4648 §5) 替换 '+', '/', '='. URL 直接可放, 不用 percent-encode.
//
// 大小估计 (典型 8 动作 plan):
//   - JSON ~600B, base64 ~800B. 装得下 URL (典型上限 2KB).
//   - 上限 ~25 动作前都安全 (≈2.5KB base64).
//
// 错误兜底:
//   - encode 失败 → nil (调用方应当 fallback 到 alert).
//   - decode 严格: base64 invalid / JSON invalid / 缺字段 → nil.
//   - 新 id 用 "plan-shared-" prefix + UUID 后缀, 避免跟原作者 plan id 冲突.
//   - autoGenerated 强制设 false (分享的 plan 是"用户的", 不是系统推荐).
//   - lastUsedAt 重置 (接收方还没练过).
enum PlanShareCodec {

    /// URL scheme + host. 改这两个 → 同步改 project.yml 的 CFBundleURLSchemes.
    static let urlScheme = "maso"
    static let urlHost = "import"
    static let urlQueryKey = "plan"

    /// 编码: Plan → base64url string. 编码失败返 nil (理论上 Codable Plan 不会失败,
    /// 但保留 nil 出口让调用方稳健).
    static func encode(_ plan: Plan) -> String? {
        let encoder = JSONEncoder()
        // ISO8601 字符串比默认 .secondsSince1970 多几个字节但语义清楚 (跨版本兼容更稳).
        // Plan 里就 2 个 Date 字段 (createdAt, updatedAt), 加 lastUsedAt 共 3 个, 多花 ~60B 可接受.
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(plan) else { return nil }
        // zlib 压缩 + "z." 前缀 — JSON 重复字段多, 压缩比 ~4×. 不压缩的 6-step plan URL ≈ 1100+
        // 字符 → QR version 30 (137 模块), 分享卡上的小 QR 根本扫不出来; 压缩后 ≈ 300 字符 →
        // version ~13, 64pt QR 可扫. 解码端保留无前缀的旧格式 fallback.
        if let compressed = try? (data as NSData).compressed(using: .zlib) as Data {
            return "z." + compressed.base64URLEncodedString()
        }
        return data.base64URLEncodedString()
    }

    /// 解码: base64url → Plan. 给新 id (prefix "plan-shared-") 防跟原作者冲突.
    /// 任何步骤失败返 nil — 调用方应当 alert "invalid link".
    static func decode(_ encoded: String) -> Plan? {
        guard let data = unwrap(encoded) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let plan = try? decoder.decode(Plan.self, from: data) else { return nil }
        return remapped(plan)
    }

    /// "z." 压缩前缀 / 旧无压缩格式 → 原始 JSON Data.
    private static func unwrap(_ encoded: String) -> Data? {
        if encoded.hasPrefix("z.") {
            return Data(base64URLEncoded: String(encoded.dropFirst(2)))
                .flatMap { try? ($0 as NSData).decompressed(using: .zlib) as Data }
        }
        return Data(base64URLEncoded: encoded)   // 旧格式 (未压缩) fallback
    }

    /// 导入侧统一重映射: 新 id 防撞 + 时间戳重置; **name/steps 原封不动** (逐组 setReps/setWeights/
    /// setDurations 都在 Plan Codable 里) — 分享出去什么, 导入回来就是什么 (owner 指定 1:1).
    private static func remapped(_ plan: Plan) -> Plan {
        let now = Date()
        let newId = "plan-shared-\(Int(now.timeIntervalSince1970))-\(UUID().uuidString.prefix(6))"
        return Plan(
            id: newId,
            name: plan.name,
            steps: plan.steps,
            createdAt: now,         // 接收方"添加"的时间, 不是原作者建 plan 的时间
            updatedAt: now,
            autoGenerated: false,   // 分享的 plan 一律算用户创建的
            lastUsedAt: nil         // 接收方还没练
        )
    }

    // MARK: 批量 (#routines-batch-share) — App Store 链接 + 数据锚点二合一 QR

    /// 批量编码: [Plan] → "z."+base64url (整组一起 zlib — JSON 键重复多, 跨计划压缩比更高).
    static func encodeMany(_ plans: [Plan]) -> String? {
        let encoder = JSONEncoder()
        encoder.dateEncodingStrategy = .iso8601
        guard let data = try? encoder.encode(plans) else { return nil }
        if let compressed = try? (data as NSData).compressed(using: .zlib) as Data {
            return "z." + compressed.base64URLEncodedString()
        }
        return data.base64URLEncodedString()
    }

    /// 批量解码 → 逐个重映射 (name/steps 1:1 不动).
    static func decodeMany(_ encoded: String) -> [Plan]? {
        guard let data = unwrap(encoded) else { return nil }
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        guard let plans = try? decoder.decode([Plan].self, from: data) else { return nil }
        return plans.map { remapped($0) }
    }

    /// 分享卡 QR 的"二合一"链接: App Store 链接 + `#ps=<数据>` 锚点.
    ///   - 没装 app 的人用相机扫 → 照常打开 App Store (fragment 是纯客户端锚点, 不影响跳转) — 宣传不丢.
    ///   - Masso 用户"从照片导入" → 读锚点 → 无损还原 (名称 + 逐组数据 1:1).
    /// 数据过大 (QR 太密, 印在卡上扫不出) → 返 nil, 调用方回落纯 App Store 链 (导入走 OCR 尽力解析).
    static func appStoreDataLink(for plans: [Plan]) -> String? {
        guard let encoded = encodeMany(plans), encoded.count <= 2000 else { return nil }
        return MasoLinks.appStore + "#ps=" + encoded
    }

    /// 照片导入的 QR 解码统一入口 — 认两种载荷:
    ///   ① App Store+锚点二合一 (`...apps.apple.com...#ps=<数据>`, 单/多计划都走这)
    ///   ② maso://import?plan= 旧单计划深链 (历史分享卡兼容)
    static func decodePlans(fromQRPayload payload: String) -> [Plan]? {
        if let r = payload.range(of: "#ps=") {
            if let plans = decodeMany(String(payload[r.upperBound...])), !plans.isEmpty {
                return plans
            }
        }
        if let url = URL(string: payload), let plan = decodePlan(from: url) {
            return [plan]
        }
        return nil
    }

    /// 生成可分享 URL: e.g. maso://import?plan=eyJpZCI6...
    /// 失败返 nil (encode 失败).
    static func shareURL(for plan: Plan) -> URL? {
        guard let encoded = encode(plan) else { return nil }
        var comps = URLComponents()
        comps.scheme = urlScheme
        comps.host = urlHost
        comps.queryItems = [URLQueryItem(name: urlQueryKey, value: encoded)]
        return comps.url
    }

    /// 拦截 onOpenURL — 校验 scheme/host, 取 query "plan", 解码 → Plan.
    /// 返 nil 时调用方应当忽略 (可能是别的 deep link, 或损坏链接).
    static func decodePlan(from url: URL) -> Plan? {
        guard url.scheme == urlScheme else { return nil }
        guard url.host == urlHost else { return nil }
        guard let comps = URLComponents(url: url, resolvingAgainstBaseURL: false) else { return nil }
        guard let encoded = comps.queryItems?.first(where: { $0.name == urlQueryKey })?.value else { return nil }
        return decode(encoded)
    }
}

// MARK: - base64url helpers
//
// RFC 4648 §5: 标准 base64 的 '+' '/' '=' 在 URL 里有特殊含义, 改成 '-' '_' 并去掉 padding '='.
// URLComponents 会帮忙 percent-encode, 但用 base64url 让 URL 字符串本身就干净 (用户复制粘贴友好).

private extension Data {
    func base64URLEncodedString() -> String {
        return self.base64EncodedString()
            .replacingOccurrences(of: "+", with: "-")
            .replacingOccurrences(of: "/", with: "_")
            .replacingOccurrences(of: "=", with: "")
    }

    init?(base64URLEncoded string: String) {
        var s = string
            .replacingOccurrences(of: "-", with: "+")
            .replacingOccurrences(of: "_", with: "/")
        // 补 padding 到 4 的倍数 (base64 要求)
        let padLen = (4 - s.count % 4) % 4
        s.append(String(repeating: "=", count: padLen))
        self.init(base64Encoded: s)
    }
}

// MARK: - RoutineImageImporter — 从图片导入训练计划 (#image-import)
//
// 两条路径, 按序尝试:
//   1. 图里有 Masso 分享卡的 QR (maso:// 深链) → 直接解码, 无损导入.
//   2. 否则 OCR (Vision, en+zh) → 逐行解析: 模糊匹配动作名 + 抓取 "3x10"/"4组×12"/"60kg"
//      → 拼成 Plan. 其他 app 的截图 / 手写计划照片都走这条 (尽力解析, 用户导入后可再编辑).

import Vision
import UIKit

// MARK: 候选数据模型

/// 一条从截图里识别出来的"疑似动作行" + 置信度. 用户在 RoutineReviewSheet 里逐条确认.
struct ImportCandidate: Identifiable, Equatable {
    var id: String = UUID().uuidString
    var ocrText: String            // 识别出的动作名原文 (做 caption; unmatched 时也当主文案)
    var sets: Int?
    var reps: Int?
    var weight: Double?
    var exerciseId: String?        // 解析到的库内动作 (high 完全匹配 / suggested 最佳猜测自动填; unmatched=nil)
    var confidence: Confidence
    var included: Bool             // 是否计入最终 routine (high/suggested 默认 true)
    enum Confidence: Int { case high, suggested, unmatched }
}

enum RoutineImportResult {
    case deepLink([Plan])                // QR 分享卡 (单/批量) — 无歧义, 整份无损导入
    case recognized([ImportCandidate])   // 第三方截图 OCR — 候选列表待用户确认 (走 RoutineReviewSheet)
    case empty                           // 没读出任何东西
}

enum RoutineImageImporter {
    /// 主入口 — Vision QR + OCR. 返回三态 (见 RoutineImportResult).
    static func analyze(from image: UIImage, library: [Exercise]) async -> RoutineImportResult {
        guard let cg = image.cgImage else { return .empty }
        // 路径 1: QR — Masso 分享卡 (App Store+锚点二合一 / 旧 maso:// 深链), 无损还原 1:1.
        if let payload = detectQR(cg),
           let plans = PlanShareCodec.decodePlans(fromQRPayload: payload), !plans.isEmpty {
            return .deepLink(plans)
        }
        // 路径 2: OCR → 置信度分级候选
        let rows = recognizeRows(cg)
        let candidates = parseCandidates(rows, library: library)
        return candidates.isEmpty ? .empty : .recognized(candidates)
    }

    private static func detectQR(_ cg: CGImage) -> String? {
        let request = VNDetectBarcodesRequest()
        request.symbologies = [.qr]
        try? VNImageRequestHandler(cgImage: cg).perform([request])
        if let s = request.results?.compactMap(\.payloadStringValue).first { return s }
        // CIDetector 兜底 — VNDetectBarcodesRequest 在模拟器和部分机型上静默失败 (返回空),
        // CIDetector 走 CPU, 哪儿都能跑. 实测模拟器上只有这条路能认出分享卡里的 QR.
        let detector = CIDetector(ofType: CIDetectorTypeQRCode, context: nil,
                                  options: [CIDetectorAccuracy: CIDetectorAccuracyHigh])
        let features = detector?.features(in: CIImage(cgImage: cg)) ?? []
        return features.compactMap { ($0 as? CIQRCodeFeature)?.messageString }.first
    }

    /// OCR → 视觉"行". 关键: 第三方 app 的训练截图是两栏布局 (左动作名, 右 "3×10 / 60kg"),
    /// Vision 会把它们拆成独立 fragment. 按 boundingBox 的 y 把同一视觉行的 fragment 重新拼回去
    /// (左→右), 这样动作名和它的组数/重量回到同一行, 解析时不再丢 metrics.
    private static func recognizeRows(_ cg: CGImage) -> [String] {
        let request = VNRecognizeTextRequest()
        request.recognitionLevel = .accurate
        request.recognitionLanguages = ["zh-Hans", "en-US"]
        request.usesLanguageCorrection = true
        try? VNImageRequestHandler(cgImage: cg).perform([request])
        struct Frag { let text: String; let minX: CGFloat; let midY: CGFloat }
        let frags: [Frag] = (request.results ?? []).compactMap { o in
            guard let s = o.topCandidates(1).first?.string else { return nil }
            let b = o.boundingBox   // 归一化, 原点左下
            return Frag(text: s, minX: b.minX, midY: b.midY)
        }
        guard !frags.isEmpty else { return [] }
        // 按 midY 从上到下排; 相邻 fragment y 接近 (一行高量级) → 归到同一行.
        let sorted = frags.sorted { $0.midY > $1.midY }
        let yTol: CGFloat = 0.018
        var rows: [[Frag]] = []
        var refY: CGFloat = .greatestFiniteMagnitude
        for f in sorted {
            if !rows.isEmpty, abs(refY - f.midY) <= yTol {
                rows[rows.count - 1].append(f)
            } else {
                rows.append([f]); refY = f.midY
            }
        }
        // 每行内左→右拼接 (用双空格分隔, 防止"名字"和"3×10"粘连成一个词)
        return rows.map { row -> String in
            let joined = row.sorted { $0.minX < $1.minX }.map(\.text).joined(separator: "  ")
            // 汉字之间的空格删掉 — Vision 常把 "跪姿腹轮" 拆成跨 box 的 "跪姿 腹轮",
            // 不删则跟库里无空格的中文名 ({"跪姿腹轮"}) 交集为空 → 完美匹配被误判成"待确认".
            // 只删"汉字 空格 汉字", 不动"汉字 数字"(组数重量要留着).
            return joined.replacingOccurrences(
                of: #"(?<=[\x{4E00}-\x{9FFF}])\s+(?=[\x{4E00}-\x{9FFF}])"#,
                with: "", options: .regularExpression)
        }
    }

    // MARK: - 置信度分级解析
    //
    // 老 bug: 用整套 searchTokens (含肌群/器械分类词) 做子串匹配 + 松散的 coversLine/singleExact
    // 接受门槛 → "Chest"/"Push Day"/合计行 这类小标题全被误判成动作, 识别过多.
    //
    // 新策略:
    //   1. 只对"动作名 token" (base + 本地化名 + variation + equipment-as-word) 做精确等值匹配,
    //      不含肌群/section/facet 分类词 → "Chest" 不再命中一堆胸部动作.
    //   2. 结构词表 (day/total/rest/星期/合计…) 先从名词里剔除.
    //   3. 三档:
    //      high      — OCR 行里出现了该动作的完整核心名 (coverEx==1 且 coverLine≥0.5) → 默认勾选加入.
    //      uncertain — 部分匹配 (coverEx≥0.5) 且有支撑 (有组数重量 或 ≥2 名词) → 醒目展示, 不默认加.
    //      unmatched — 没好匹配但有组数重量+像样名字 → 提示从库里换一个 (不提供存为自创 — 有 Pro gate).
    //      其余 (小标题/噪音) → 直接丢.

    /// 动作名预索引 (只算名字相关 token, 排除肌群/器械分类词).
    private struct ExIndex {
        let id: String
        let displayName: String
        let cores: [Set<String>]      // 核心名候选 (英文 base / 本地化名), 覆盖率取最大者
        let nameTokens: Set<String>   // 全部名字 token (精确等值)
    }

    private static func buildIndex(_ library: [Exercise]) -> [ExIndex] {
        library.map { ex in
            let baseWords = Set(exerciseSearchWords(ex.nameParts?.base ?? ex.name))
            let dispWords = Set(exerciseSearchWords(ex.displayName))
            var cores: [Set<String>] = []
            if !baseWords.isEmpty { cores.append(baseWords) }
            if !dispWords.isEmpty, dispWords != baseWords { cores.append(dispWords) }
            var nameTokens = baseWords.union(dispWords)
            nameTokens.formUnion(exerciseSearchWords(ex.name))
            if let v = ex.nameParts?.variation { nameTokens.formUnion(exerciseSearchWords(v)) }
            if let e = ex.nameParts?.equipment { nameTokens.formUnion(exerciseSearchWords(e)) }
            return ExIndex(id: ex.id, displayName: ex.displayName, cores: cores, nameTokens: nameTokens)
        }
    }

    /// 结构词 — 截图里的小标题/合计/星期/日期/休息行/逐组标注等, 绝不是动作名. 命中即剔除.
    private static let structuralWords: Set<String> = [
        // ⚠️ 别加 split/squat/press/row/fly/curl/raise/pull/push/walk/hold 这类 — 它们是真动作名词.
        "day","days","week","weeks","workout","workouts","session","sessions","routine","routines",
        "plan","program","total","totals","volume","summary","history","exercise","exercises",
        "warmup","warm","warmups","cooldown","cool","superset","supersets","circuit","drop","dropset","dropsets","notes","note",
        "tempo","rpe","rir","pr","prs","date","today","yesterday","tomorrow","am","pm","time","duration","est",
        "completed","complete","finished","done","best","goal","target","prev","previous","last",
        // 逐组/强度标注行 ("Warm-up set" / "To failure" / "AMRAP" / "Working sets") — 不是动作
        "failure","fail","amrap","emom","burnout","working","backoff",
        "kcal","cal","calories","bpm","avg","average",
        "mon","tue","tues","wed","weds","thu","thur","thurs","fri","sat","sun",
        "monday","tuesday","wednesday","thursday","friday","saturday","sunday",
        "jan","feb","mar","apr","may","jun","jul","aug","sep","sept","oct","nov","dec",
        // zh
        "训练","计划","组数","次数","休息","热身","放松","总计","合计","时长","时间","周","天","动作","备注",
        "完成","今天","昨天","明天","星期","周一","周二","周三","周四","周五","周六","周日","上午","下午","分钟","训练日",
        // zh 逐组/强度/统计标注
        "力竭","递减","递减组","热身组","正式组","组间","卡路里","千卡","心率","平均","容量","强度","自重",
    ]
    /// 计量词 — 不参与动作名匹配. 注意不放单字母 "x"/"s": "NxM" 已被正则提前剥掉,
    /// 留单字母在这里反而会吃掉 "X-bar"/"farmer's" 里的 x/s.
    private static let metricStop: Set<String> = [
        "sets","set","reps","rep","kg","lb","lbs","kgs","组","次","rest","min","mins","sec","secs",
    ]

    /// OCR 识别到的重量统一成 kg — PlanStep.weight 全 app 规范单位是 kg (显示时再按用户单位换算).
    /// lb/lbs/磅 → ×0.45359237 转 kg, 四舍五入到 0.5 (跟杠片粒度一致, 避免 61.23 这类碎数);
    /// kg/公斤 (或没捕获到单位) 原样返回.
    private static func weightInKg(_ value: Double, unit: String?) -> Double {
        guard let u = unit?.lowercased(), u.hasPrefix("lb") || u.contains("磅") else { return value }
        return (value * 0.45359237 * 2).rounded() / 2
    }

    private static func parseCandidates(_ lines: [String], library: [Exercise]) -> [ImportCandidate] {
        let index = buildIndex(library)
        // token 文档频率 — 一个词出现在多少个动作名里. back/press/row/biceps 这类高频词
        // 单独命中毫无辨识度 (库里几十个动作都含它), 不足以把一行立成 suggested 候选.
        var tokenDF: [String: Int] = [:]
        for idx in index {
            for t in idx.nameTokens { tokenDF[t, default: 0] += 1 }
        }
        // 各家 app 的 sets/reps/weight 写法全谱 (caseInsensitive — OCR 常把 × 读成大写 "X"):
        //   "3 × 10"        sets × reps          (Strong 等)
        //   "2 × 卧推"      组数前缀动作名 → 2 组  (Hevy 计划页)
        //   "卧推 × 3"      尾缀 → 3 组           (手写/备忘)
        //   "60 kg × 8"     重量 × 次数           (Strong 逐组行 — × 不是组数!)
        //   "8 × 60 kg"     次数 × 重量
        //   "3 sets of 12" / "12 reps" / "4组×12" / "12次"
        let setsReps = try! NSRegularExpression(pattern: #"(\d{1,2})\s*[x×*]\s*(\d{1,3})|(\d{1,2})\s*组\s*[x×*]?\s*(\d{1,3})?"#, options: [.caseInsensitive])
        let setsWords = try! NSRegularExpression(pattern: #"(\d{1,2})\s*sets?\b(?:\s*(?:[x×*·]|of)\s*(\d{1,3}))?"#, options: [.caseInsensitive])
        let repsWords = try! NSRegularExpression(pattern: #"(\d{1,3})\s*(?:reps?\b|次)"#, options: [.caseInsensitive])
        // 单位改成捕获组 — lb/磅 命中时要换算成 kg 落库 (PlanStep.weight 全 app 规范单位是 kg).
        let weightRe = try! NSRegularExpression(pattern: #"(\d+(?:\.\d+)?)\s*(kg|公斤|lbs?|磅)"#, options: [.caseInsensitive])
        // 重量×次数 (正/反两向) — 必须先于 N×M 判定, 否则 "60 kg × 8" 会被误读成 60 组.
        let weightXreps = try! NSRegularExpression(pattern: #"(\d+(?:\.\d+)?)\s*(kg|公斤|lbs?|磅)\s*[x×*]\s*(\d{1,3})\b"#, options: [.caseInsensitive])
        let repsXweight = try! NSRegularExpression(pattern: #"(\d{1,3})\s*[x×*]\s*(\d+(?:\.\d+)?)\s*(kg|公斤|lbs?|磅)"#, options: [.caseInsensitive])
        // 组数前缀/尾缀动作名: "2 × <名字>" / "<名字> × 3" — × 一侧是数字另一侧是文字 → 数字是组数.
        let leadingSets = try! NSRegularExpression(pattern: #"^\s*(\d{1,2})\s*[x×*]\s*(?=[^\d\s])"#, options: [.caseInsensitive])
        let trailingSets = try! NSRegularExpression(pattern: #"(?<=[^\d\s.])\s*[x×*]\s*(\d{1,2})\s*$"#, options: [.caseInsensitive])
        var out: [ImportCandidate] = []
        var usedIds = Set<String>()
        /// 已立项候选行的全部名字词 — 回顾行守卫用 (底部摘要卡重复动作名 → 不再立项).
        var seenTokens = Set<String>()
        var lastCandLine = -10
        // 行分组后大多 metrics 已跟名字同行; 但有的 app 把 "3×10 / 60kg" 排在动作名 *上面* 一行,
        // 那个纯数值行回填不到"上一个候选"(还没建) → 暂存, 给下一个建出来的候选用.
        var pending: (sets: Int?, reps: Int?, weight: Double?)? = nil
        for (i, raw) in lines.enumerated() {
            let line = raw.trimmingCharacters(in: .whitespaces)
            guard line.count >= 2 else { continue }
            let ns = line as NSString
            var sets: Int? = nil, reps: Int? = nil, weight: Double? = nil
            func grp(_ m: NSTextCheckingResult, _ idx: Int) -> String? {
                let r = m.range(at: idx); return r.location == NSNotFound ? nil : ns.substring(with: r)
            }
            let full = NSRange(location: 0, length: ns.length)
            // ① 重量×次数 (两向) — 优先消化带单位的 ×, 防止被当成组数.
            //   单位组一并捕获: "135 lbs × 8" → 61 kg (不再把磅数原样当 kg 落库).
            if let m = weightXreps.firstMatch(in: line, range: full) {
                weight = grp(m, 1).flatMap(Double.init).map { weightInKg($0, unit: grp(m, 2)) }
                reps = grp(m, 3).flatMap(Int.init)
            } else if let m = repsXweight.firstMatch(in: line, range: full) {
                reps = grp(m, 1).flatMap(Int.init)
                weight = grp(m, 2).flatMap(Double.init).map { weightInKg($0, unit: grp(m, 3)) }
            }
            // ② N×M (纯数字两侧) → sets × reps. ①命中过则跳过 (那个 × 已是重量语义).
            if reps == nil, weight == nil,
               let m = setsReps.firstMatch(in: line, range: full) {
                sets = (grp(m, 1) ?? grp(m, 3)).flatMap(Int.init)
                reps = (grp(m, 2) ?? grp(m, 4)).flatMap(Int.init)
            }
            // ③ "N sets [of M]"
            if sets == nil, let m = setsWords.firstMatch(in: line, range: full) {
                sets = grp(m, 1).flatMap(Int.init)
                if reps == nil { reps = grp(m, 2).flatMap(Int.init) }
            }
            // ④ "M reps / M次"
            if reps == nil, let m = repsWords.firstMatch(in: line, range: full) {
                reps = grp(m, 1).flatMap(Int.init)
            }
            // ⑤ 组数前缀/尾缀动作名: "2 × 卧推" / "卧推 × 3" → 组数 (Hevy 计划页格式).
            if sets == nil, let m = leadingSets.firstMatch(in: line, range: full) {
                sets = grp(m, 1).flatMap(Int.init)
            }
            if sets == nil, weight == nil, let m = trailingSets.firstMatch(in: line, range: full) {
                sets = grp(m, 1).flatMap(Int.init)
            }
            // ⑥ 裸重量 (没参与 ①的 ×) — 同样按单位组换算 kg
            if weight == nil, let m = weightRe.firstMatch(in: line, range: full),
               m.range(at: 1).location != NSNotFound {
                weight = Double(ns.substring(with: m.range(at: 1))).map { weightInKg($0, unit: grp(m, 2)) }
            }
            let hasMetrics = sets != nil || reps != nil || weight != nil
            // 去掉数字/单位后的纯文本 → 搜索词
            let nameText = line
                .replacingOccurrences(of: #"\d+(?:\.\d+)?\s*(?:kg|公斤|lbs?|磅)\s*[x×*]\s*\d{1,3}"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"\d+(?:\.\d+)?\s*(?:kg|公斤|lbs?|磅)"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"\d{1,2}\s*[x×*]\s*\d{1,3}"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"\d{1,3}\s*(?:reps?\b|次)"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"^\s*\d{1,2}\s*[x×*]\s*"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"\s*[x×*]\s*\d{1,2}\s*$"#, with: " ", options: [.regularExpression, .caseInsensitive])
                .replacingOccurrences(of: #"\d{1,2}\s*组"#, with: " ", options: .regularExpression)
            let matchWords = exerciseSearchWords(nameText).filter { Int($0) == nil && !metricStop.contains($0) }
            let contentWords = matchWords.filter { !structuralWords.contains($0) }
            // 纯数值/纯结构行 (没有动作名词) — 把组数/重量回填到紧邻的上一个候选 (±2 行内), 然后跳过.
            // (很多 app 把动作名和 "3×8 · 60kg" 拆成相邻两行, 或 per-set 行 "Set 1  60kg".)
            if contentWords.isEmpty {
                // 汇总/标注行守卫: 行里出现了结构词 ("5 exercises · 14 sets" / "总计 14 组" /
                // "Warm-up 60kg×8") → 它的数字是统计/热身, 不是上一个动作的组数 — 不回填不暂存.
                let isStructuralRow = matchWords.contains { structuralWords.contains($0) }
                if hasMetrics, !isStructuralRow {
                    if i - lastCandLine <= 2, var last = out.last {
                        if let v = sets { last.sets = v }
                        if let v = reps { last.reps = v }
                        if let v = weight { last.weight = v }
                        out[out.count - 1] = last
                    } else {
                        pending = (sets, reps, weight)   // 名字还没来 → 暂存给下一个候选
                    }
                }
                continue
            }
            // 标题/分组头守卫: 行里出现结构词 (Day/Week/Push Day/总计…) 且整行没有任何
            // 组数/次数/重量 → 这是 routine 标题或分组小标题, 不是动作行. 直接丢 —
            // 否则 "Day B · Back + Biceps" 里的 back 会撞上 "背伸" 这类动作的 50% 核心名,
            // 凭空多出一个动作 (用户报: 图里 5 个训练识别出 6 个).
            let hasStructural = matchWords.contains { structuralWords.contains($0) }
            if hasStructural, !hasMetrics { continue }
            // 名字行自己没读到 metrics, 但前一行 (动作名上方) 攒了一组 → 用它.
            if !hasMetrics, let p = pending { sets = p.sets; reps = p.reps; weight = p.weight }
            pending = nil
            let W = Set(contentWords)
            // 回顾行守卫: 无 metrics 的行, 词几乎全是前面候选已经出现过的 (≥80% 覆盖) →
            // 这是截图里弹窗底下露出的"收起卡片"/底部摘要 ("A, B, C, …" 逗号串) 在重复
            // 已识别的动作名 — 不是新动作. (实测 Strong 的 routine 弹窗截图: 背景摘要卡的
            // "Wide-grip back shrug…" 撞上 "Lat Pulldown (Wide Grip)" 多出第 6 行.)
            if sets == nil && reps == nil && weight == nil, !W.isEmpty,
               Double(W.intersection(seenTokens).count) / Double(W.count) >= 0.8 {
                continue
            }
            // 最佳匹配 — 双向覆盖, 防止 "Cable Fly" 误命中 "反握上斜飞鸟" 这类同根词变种:
            //   precision = OCR 行覆盖了该动作"核心名"的比例 (行里有没有这个动作的完整名字).
            //   recall    = 该行的词被该动作名 (核心+器械) 解释的比例 (行里有没有别的没法解释的词).
            // high 要求 precision==1 且 recall==1 → "完全对应": 行里正好就是这个动作, 没有多余的词.
            var best: (idx: ExIndex, precision: Double, recall: Double, coreLen: Int)? = nil
            for idx in index {
                let hits = W.intersection(idx.nameTokens).count
                guard hits > 0 else { continue }
                var precision = 0.0
                var coreLen = 0
                for c in idx.cores {
                    let p = Double(c.intersection(W).count) / Double(c.count)
                    if p > precision || (p == precision && c.count > coreLen) { precision = p; coreLen = c.count }
                }
                let recall = Double(hits) / Double(W.count)
                let better: Bool
                if let cur = best {
                    better = precision > cur.precision
                        || (precision == cur.precision && recall > cur.recall)
                        || (precision == cur.precision && recall == cur.recall && coreLen > cur.coreLen)
                        // 全平局 → 选名字 token 最少的 = 最朴素的那个变种 ("Bench Press" 取"卧推",
                        // 不取"交替卧推(哑铃)"; 用户写了限定词才会命中带 variation/equipment 的).
                        || (precision == cur.precision && recall == cur.recall && coreLen == cur.coreLen && idx.nameTokens.count < cur.idx.nameTokens.count)
                } else { better = true }
                if better { best = (idx, precision, recall, coreLen) }
            }
            let name = cleanName(line)
            var cand: ImportCandidate? = nil
            // suggested 的"匹配强度"门槛: 命中 ≥2 个名字词; 单词命中必须是低频特异词
            // (库内 ≤8 个动作含它, 且 ≥4 拉丁字符或含汉字) — "pushdown"/"划船" 这种算数,
            // "back"/"biceps"/"up" 这种高频词单独命中不算 — 防 "Warm-up 60kg×8" 的孤词 "up"
            // 或标题残词撞上某个两词名的 50% 就被造出幽灵动作 (图里 5 个训练识别出 6 个).
            func matchStrongEnough(_ b: (idx: ExIndex, precision: Double, recall: Double, coreLen: Int)) -> Bool {
                let matched = W.intersection(b.idx.nameTokens)
                if matched.count >= 2 { return true }
                return matched.contains { w in
                    (tokenDF[w] ?? 0) <= 8 &&
                    (w.count >= 4 || w.unicodeScalars.contains { $0.properties.isIdeographic })
                }
            }
            if let b = best, b.precision >= 0.999, b.recall >= 0.999, !usedIds.contains(b.idx.id) {
                // high — 行里正好就是这个动作 (核心名全在 + 没多余词) → 默认加入.
                usedIds.insert(b.idx.id)
                cand = ImportCandidate(ocrText: name, sets: sets, reps: reps, weight: weight,
                                       exerciseId: b.idx.id, confidence: .high, included: true)
            } else if let b = best, b.precision >= 0.5, matchStrongEnough(b),
                      !usedIds.contains(b.idx.id),
                      // 无 metrics 的行只有"完整核心名都在"才可立 suggested — 部分匹配 + 连组数
                      // 都没有, 几乎都是背景 UI 残文 (摘要卡/按钮), 不是动作行.
                      hasMetrics || b.precision >= 0.999 {
                // suggested — 部分匹配 → 自动采用最佳猜测并默认加入; UI 虚线框 + 识别原文 caption + 替换按钮.
                usedIds.insert(b.idx.id)
                cand = ImportCandidate(ocrText: name, sets: sets, reps: reps, weight: weight,
                                       exerciseId: b.idx.id, confidence: .suggested, included: true)
            } else if sets != nil || reps != nil, substantial(contentWords) {
                // unmatched — 库里没像样匹配 → 默认不勾, 展示识别原文, 用户可替换成库内动作.
                // 门槛收紧到"有组数/次数"才立行 — 裸重量行 ("Top 100 kg" 之类逐组标注) 不再
                // 凭一个杂词就多出一行, 训练个数跟图里对得上.
                cand = ImportCandidate(ocrText: name, sets: sets, reps: reps, weight: weight,
                                       exerciseId: nil, confidence: .unmatched, included: false)
            }
            if let c = cand, !c.ocrText.isEmpty {
                out.append(c)
                lastCandLine = i
                seenTokens.formUnion(W)   // 回顾行守卫的语料 — 这行的词以后再整行出现就是摘要
            }
        }
        return out
    }

    /// 是否含"像样的名字词" — ≥3 个拉丁字符, 或 ≥2 个汉字. 防止把 "Set"/"x2" 这种残渣当自创动作.
    private static func substantial(_ words: [String]) -> Bool {
        words.contains { w in
            if w.count >= 3 { return true }
            return w.count >= 2 && w.unicodeScalars.contains { $0.properties.isIdeographic }
        }
    }

    /// 清掉行里的数字/单位/分隔符, 留下展示用的动作名原文 (保留大小写).
    private static func cleanName(_ line: String) -> String {
        var s = line
        let pats = [
            #"\d+(?:\.\d+)?\s*(?:kg|公斤|lbs?|磅)\s*[x×*]\s*\d{1,3}"#,
            #"\d+(?:\.\d+)?\s*(?:kg|公斤|lbs?|磅)"#,
            #"\d{1,2}\s*sets?\b(?:\s*(?:[x×*·]|of)\s*\d{1,3})?"#,
            #"\d{1,2}\s*[x×*]\s*\d{1,3}"#,
            #"\d{1,2}\s*组(?:\s*[x×*]?\s*\d{1,3})?"#,
            #"\d{1,3}\s*(?:reps?\b|次)"#,
            #"^\s*\d{1,2}\s*[x×*]\s*"#,
            #"\s*[x×*]\s*\d{1,2}\s*$"#,
        ]
        for p in pats {
            s = s.replacingOccurrences(of: p, with: " ", options: [.regularExpression, .caseInsensitive])
        }
        s = s.replacingOccurrences(of: #"[·•|,:;]+"#, with: " ", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\s+"#, with: " ", options: .regularExpression)
        return s.trimmingCharacters(in: .whitespacesAndNewlines)
    }
}
