import Foundation

// 训练计划的一个步骤 (= web 端 PlanStep)
struct PlanStep: Identifiable, Hashable, Codable, Sendable {
    let id: String
    let exerciseId: String
    var sets: Int = 1
    var reps: Int?
    var weight: Double?
    /// 逐组覆盖 (#3) — 用户在训练中开"每组不同重量"后存. nil 数组 = 全组用统一 reps/weight;
    /// 数组里某项 nil = 该组回退统一值. 长度通常 == sets (短了/长了都按 index 安全取).
    var setReps: [Int?]? = nil
    var setWeights: [Double?]? = nil
    /// 逐组时长覆盖 (计时类动作 — 平板支撑等). 用户训练中途改过某组时长后存. 语义同 setReps/setWeights:
    /// nil 数组 = 全组用统一 duration; 数组里某项 nil = 该组回退 duration. Codable 默认 nil → 旧数据/旧 QR 兼容.
    var setDurations: [Int?]? = nil
    /// 有氧 / 灵活性段的时长 (秒); strength 则为 nil
    var duration: Int?
    /// 组间休息 (秒)
    var restBetweenSets: Int = 90
    /// 步骤之间额外的休息 (秒); 默认 0
    var rest: Int = 0

    /// 第 n 组 (1-based) 的目标 reps — 有逐组覆盖用它, 否则回退统一 reps.
    func repsForSet(_ n: Int) -> Int? {
        if let arr = setReps, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return reps
    }
    /// 第 n 组 (1-based) 的目标 weight — 有逐组覆盖用它, 否则回退统一 weight.
    func weightForSet(_ n: Int) -> Double? {
        if let arr = setWeights, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return weight
    }
    /// 第 n 组 (1-based) 的目标 duration (秒) — 有逐组覆盖用它, 否则回退统一 duration.
    func durationForSet(_ n: Int) -> Int? {
        if let arr = setDurations, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return duration
    }
    /// 是否启用了逐组不同 (任一 set 数组非空).
    var hasPerSetOverrides: Bool {
        (setReps?.isEmpty == false) || (setWeights?.isEmpty == false) || (setDurations?.isEmpty == false)
    }
}

// 训练计划 (= web 端 Plan)
/// 一条 routine 的来源 — 决定列表里挂 AI / Classics 标签.
enum PlanSource: String, Codable, Hashable, Sendable {
    case custom    // 用户自建 / 系统推荐种子 — 不挂标签
    case ai        // AI 生成
    case classics  // 从 Classics(经典模板)采纳
}

struct Plan: Identifiable, Hashable, Codable, Sendable {
    let id: String
    var name: String
    var steps: [PlanStep]
    var createdAt: Date
    var updatedAt: Date
    /// 是否为系统自动生成 (推荐计划 / 自由训练即时合成的)
    var autoGenerated: Bool = false
    var lastUsedAt: Date?
    /// 来源 (AI / Classics / 自建). optional + nil: 旧数据缺这个 key 也能解码 (跟 SetRecord.planName 同套路).
    var source: PlanSource? = nil

    /// 解析后的来源: 有显式 source 用它; 否则按 id 前缀兜底 (旧数据 / savePlan 重 id 前的); 都不命中 → custom.
    var resolvedSource: PlanSource {
        if let source { return source }
        if id.hasPrefix("plan-ai-") { return .ai }
        if id.hasPrefix("plan-community-") { return .classics }
        return .custom
    }
}

// 历史记录 (= web 端 SetRecord)
struct SetRecord: Identifiable, Hashable, Codable, Sendable {
    let id: String
    let exerciseId: String
    let exerciseName: String
    let category: ExerciseCategory
    var weight: Double?
    var reps: Int?
    var duration: Int?
    let performedAt: Date
    var planId: String?
    /// 落库时的 plan 名快照 — plan 之后被删, 历史卡名不再退化成"自由训练".
    /// optional + 默认 nil: 旧记录缺这个 key 也能解码 (沿用原 fallback 链).
    var planName: String? = nil
}
