import Foundation

// 训练计划的一个步骤 (= web 端 PlanStep)
struct PlanStep: Identifiable, Hashable, Codable, Sendable {
    let id: String
    let exerciseId: String
    var sets: Int = 1
    var reps: Int?
    var weight: Double?
    /// 逐组覆盖 (#3) — 用户在训练中开"每组不同重量"后存. nil 数组 = 全组用统一 reps/weight;
    /// 数组里某项 nil = 该组回退统一值. 长度通常 == sets (短了/长了都按 index 安全取).
    var setReps: [Int?]? = nil
    var setWeights: [Double?]? = nil
    /// 逐组时长覆盖 (计时类动作 — 平板支撑等). 用户训练中途改过某组时长后存. 语义同 setReps/setWeights:
    /// nil 数组 = 全组用统一 duration; 数组里某项 nil = 该组回退 duration. Codable 默认 nil → 旧数据/旧 QR 兼容.
    var setDurations: [Int?]? = nil
    /// 有氧 / 灵活性段的时长 (秒); strength 则为 nil
    var duration: Int?
    /// 组间休息 (秒)
    var restBetweenSets: Int = 90
    /// 步骤之间额外的休息 (秒); 默认 0
    var rest: Int = 0

    /// 第 n 组 (1-based) 的目标 reps — 有逐组覆盖用它, 否则回退统一 reps.
    func repsForSet(_ n: Int) -> Int? {
        if let arr = setReps, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return reps
    }
    /// 第 n 组 (1-based) 的目标 weight — 有逐组覆盖用它, 否则回退统一 weight.
    func weightForSet(_ n: Int) -> Double? {
        if let arr = setWeights, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return weight
    }
    /// 第 n 组 (1-based) 的目标 duration (秒) — 有逐组覆盖用它, 否则回退统一 duration.
    func durationForSet(_ n: Int) -> Int? {
        if let arr = setDurations, arr.indices.contains(n - 1), let v = arr[n - 1] { return v }
        return duration
    }
    /// 是否启用了逐组不同 (任一 set 数组非空).
    var hasPerSetOverrides: Bool {
        (setReps?.isEmpty == false) || (setWeights?.isEmpty == false) || (setDurations?.isEmpty == false)
    }
}

// 训练计划 (= web 端 Plan)
/// 一条 routine 的来源 — 决定列表里挂 AI / Classics 标签.
enum PlanSource: String, Codable, Hashable, Sendable {
    case custom    // 用户自建 / 系统推荐种子 — 不挂标签
    case ai        // AI 生成
    case classics  // 从 Classics(经典模板)采纳
    /// **本地规则生成** — AI 够不到时由内置模板 + LocalRoutineRules 拼出来的.
    /// 单独一档而不是并进 .custom: 用户在 Coach 里明明是让 AI 生成, 结果拿到的不是 AI 的东西,
    /// 必须让他看得出来 —— 否则跟他自己手建的 routine 长得一模一样, 等于默默糊弄.
    case builtIn
}

/// 一条"生成依据" —— 用户提过、并且**已经被强制执行**的约束.
/// label 在生成那一刻就本地化好并存下来: 计划是历史记录, 事后换语言不该改写当时的凭据.
struct PlanConstraint: Codable, Hashable, Identifiable, Sendable {
    enum Kind: String, Codable, Sendable {
        case equipment     // 只用哑铃 / 徒手
        case duration      // 45 分钟以内
        case avoid         // 不练腿 (含伤病规避)
        case focus         // 多练胸
    }
    let kind: Kind
    /// 机器可读值 (equipment=EquipmentCategory.rawValue / duration=分钟数 / avoid|focus=MuscleGroup.rawValue)
    let value: String
    /// 展示用短语, e.g. "Dumbbells only" / "45 min cap" / "No legs"
    let label: String

    var id: String { "\(kind.rawValue):\(value)" }

    var icon: String {
        switch kind {
        case .equipment: return "dumbbell"
        case .duration:  return "clock"
        case .avoid:     return "hand.raised"
        case .focus:     return "target"
        }
    }
}

struct Plan: Identifiable, Hashable, Codable, Sendable {
    let id: String
    var name: String
    var steps: [PlanStep]
    var createdAt: Date
    var updatedAt: Date
    /// 是否为系统自动生成 (推荐计划 / 自由训练即时合成的)
    var autoGenerated: Bool = false
    var lastUsedAt: Date?
    /// 来源 (AI / Classics / 自建). optional + nil: 旧数据缺这个 key 也能解码 (跟 SetRecord.planName 同套路).
    var source: PlanSource? = nil
    /// AI 生成时 LLM 给出的一句话理由 (为什么这么排) — 露在卡片上, 让用户一眼看出"这是真 AI". 仅 .ai 计划有.
    var rationale: String? = nil

    /// 生成这份计划时用户提的约束 (只有哑铃 / 45 分钟 / 不练腿 …) —— **契约**, 不是装饰.
    ///
    /// 为什么要存进 Plan: 竞品调研里 6 个不同开发商的用户在骂同一件事 —— "我明明填了器械/伤病,
    /// 它生成的还是用我没有的机器"。空白不在"能不能表达", 在"表达完到底算不算数"。
    /// 所以这里做两件事: ① 生成后**硬过滤**一遍 (见 LocalRoutineRules.apply);
    /// ② 把当时依据的约束钉在计划上给用户看见 —— 他能自己核对 app 有没有说到做到.
    ///
    /// ⚠️ 必须 Optional: Plan 会整体落盘, Swift 合成的 Codable 对**缺失的 key 直接抛错**,
    ///    老用户的存档里没有这个字段 (跟 Session.completionOrder / Plan.source 同一个坑).
    var constraints: [PlanConstraint]? = nil

    /// 解析后的来源: 有显式 source 用它; 否则按 id 前缀兜底 (旧数据 / savePlan 重 id 前的); 都不命中 → custom.
    var resolvedSource: PlanSource {
        if let source { return source }
        if id.hasPrefix("plan-ai-") { return .ai }
        if id.hasPrefix("plan-community-") { return .classics }
        return .custom
    }
}

// 历史记录 (= web 端 SetRecord)
struct SetRecord: Identifiable, Hashable, Codable, Sendable {
    let id: String
    let exerciseId: String
    let exerciseName: String
    let category: ExerciseCategory
    var weight: Double?
    var reps: Int?
    var duration: Int?
    let performedAt: Date
    var planId: String?
    /// 落库时的 plan 名快照 — plan 之后被删, 历史卡名不再退化成"自由训练".
    /// optional + 默认 nil: 旧记录缺这个 key 也能解码 (沿用原 fallback 链).
    var planName: String? = nil
}
