#!/usr/bin/env python3
"""把 exercises.json 里 873 个动作名字翻译成多语言 .strings 文件.

策略:
1. PHRASE_ZH 长短语优先匹配 (整名命中或子串命中)
2. WORD_ZH 单词级 fallback (剩余英文词替换)
3. 保留 word order 大致英文顺序 (修饰前置, 跟中文习惯一致)
4. 未识别词保留英文 (用户后续可手工补)

输出: Maso/Resources/<lang>.lproj/ExerciseNames.strings
       格式 "EnglishName" = "翻译"; 一行一条
"""
import json
import re
import os
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
JSON_PATH = os.path.join(REPO_ROOT, 'Maso/Resources/exercises.json')

# ─── 整名直翻 (最高优先级, 完全匹配 lower-case 整名) ───
EXACT_ZH = {
    "deadlift": "硬拉",
    "squat": "深蹲",
    "bench press": "卧推",
    "pull-up": "引体向上",
    "push-up": "俯卧撑",
    "chin-up": "正握引体向上",
    "plank": "平板支撑",
    "burpee": "波比跳",
    "dip": "双杠臂屈伸",
}

# ─── 短语级翻译 (子串匹配, 长的先匹配) ───
# 用整短语命中提高准确度. 顺序: 越长越先.
PHRASE_ZH = [
    # 用户走查后发现缺的高频
    ("pullup", "引体向上"),
    ("pullups", "引体向上"),
    ("pushup", "俯卧撑"),
    ("pushups", "俯卧撑"),
    ("situp", "仰卧起坐"),
    ("situps", "仰卧起坐"),
    ("chinup", "正握引体向上"),
    ("chinups", "正握引体向上"),
    ("v-bar", "V 杆"),
    ("v bar", "V 杆"),
    ("side lateral", "侧平举"),
    ("internal rotation", "内旋"),
    ("external rotation", "外旋"),
    ("hammer curls", "锤式弯举"),
    ("cat stretch", "猫式拉伸"),
    ("dog stretch", "下犬式"),
    ("cat pose", "猫式"),
    ("rope attachment", "绳索附件"),
    ("calf stretch", "小腿拉伸"),
    ("chest stretch", "胸部拉伸"),
    ("hamstring stretch", "腿后腱拉伸"),
    ("quad stretch", "股四头拉伸"),
    ("shoulder stretch", "肩部拉伸"),
    ("hip stretch", "髋部拉伸"),
    ("groin stretch", "腹股沟拉伸"),
    ("triceps stretch", "三头拉伸"),
    ("biceps stretch", "二头拉伸"),
    ("back stretch", "背部拉伸"),
    ("neck stretch", "颈部拉伸"),
    ("car deadlift", "汽车硬拉"),
    ("car drivers", "Car Drivers"),
    ("rack pull", "架上拉"),
    ("rack pulls", "架上拉"),
    ("face pull", "面拉"),
    ("scapular pull-up", "肩胛引体"),
    ("scapular pullup", "肩胛引体"),
    ("rocky pull-ups", "Rocky 引体"),
    ("body-up", "起身"),
    ("body up", "起身"),
    ("butt-ups", "臀部抬起"),
    ("butt ups", "臀部抬起"),
    ("anterior tibialis-smr", "胫前肌肌筋膜放松"),
    ("anterior tibialis", "胫前肌"),
    ("brachialis-smr", "肱肌肌筋膜放松"),
    ("calves-smr", "小腿肌筋膜放松"),
    ("upper back-smr", "上背肌筋膜放松"),
    ("groin-smr", "腹股沟肌筋膜放松"),
    ("glutes-smr", "臀部肌筋膜放松"),
    ("hamstrings-smr", "腿后腱肌筋膜放松"),
    ("quads-smr", "股四头肌筋膜放松"),
    ("it band-smr", "髂胫束肌筋膜放松"),
    ("piriformis-smr", "梨状肌肌筋膜放松"),
    ("adductor-smr", "内收肌肌筋膜放松"),
    ("lats-smr", "背阔肌肌筋膜放松"),
    ("guillotine bench press", "断头台卧推"),
    ("rear-delt", "后束三角肌"),
    ("rear delt", "后束三角肌"),
    ("low pulley", "低位滑轮"),
    ("high pulley", "高位滑轮"),
    ("inverted row", "反向划船"),
    ("around the back", "绕背"),
    ("anti-gravity press", "反重力推举"),
    ("good morning", "早安式"),
    ("the worlds", "世界"),
    ("worlds", "世界"),
    ("see-saw press", "翘翘板推举"),
    ("see saw press", "翘翘板推举"),
    ("renegade row", "Renegade 划船"),

    # 复合动作 (高频)
    ("ab roller", "腹肌轮"),
    ("ab wheel", "腹肌轮"),
    ("ab crunch", "卷腹"),
    ("ab crunch machine", "卷腹器械"),
    ("crunches", "卷腹"),
    ("pull ups", "引体向上"),
    ("pull-ups", "引体向上"),
    ("push ups", "俯卧撑"),
    ("push-ups", "俯卧撑"),
    ("sit ups", "仰卧起坐"),
    ("sit-ups", "仰卧起坐"),
    ("chin ups", "正握引体向上"),
    ("chin-ups", "正握引体向上"),
    ("step ups", "登阶"),
    ("step-ups", "登阶"),
    ("dips", "双杠臂屈伸"),
    ("atlas stones", "阿特拉斯石"),
    ("atlas stone", "阿特拉斯石"),
    ("balance board", "平衡板"),
    ("bench dip", "卧推凳臂屈伸"),
    ("bench dips", "卧推凳臂屈伸"),
    ("anti-gravity", "反重力"),
    ("anti gravity", "反重力"),
    ("body-up", "起身"),
    ("body up", "起身"),
    ("bottoms up", "底部向上"),
    ("bottoms-up", "底部向上"),
    ("around the world", "环绕"),
    ("around the worlds", "环绕"),
    ("around the back", "绕背"),
    ("behind the back", "背后"),
    ("behind the neck", "颈后"),
    ("behind the head", "头后"),
    ("face down", "面朝下"),
    ("face up", "面朝上"),
    ("pull over", "屈臂上拉"),
    ("pullover", "屈臂上拉"),
    ("pullovers", "屈臂上拉"),
    ("pull through", "穿拉"),
    ("pull-through", "穿拉"),
    ("low pulley", "低位滑轮"),
    ("high pulley", "高位滑轮"),
    ("two-arm", "双臂"),
    ("two arm", "双臂"),
    ("two-dumbbell", "双哑铃"),
    ("two dumbbell", "双哑铃"),
    ("one-arm", "单臂"),
    ("one arm", "单臂"),
    ("one-leg", "单腿"),
    ("one leg", "单腿"),
    ("one-handed", "单手"),
    ("one hand", "单手"),
    ("bent over", "俯身"),
    ("bent-over", "俯身"),
    ("bent arm", "屈臂"),
    ("bent-arm", "屈臂"),
    ("bent leg", "屈腿"),
    ("bent-leg", "屈腿"),
    ("good morning", "早安式"),
    ("battling ropes", "战绳"),
    ("battle ropes", "战绳"),
    ("medicine ball", "药球"),
    ("stability ball", "瑜伽球"),
    ("swiss ball", "瑞士球"),
    ("foam roller", "泡沫滚筒"),
    ("foam rolling", "泡沫滚筒放松"),
    ("hand walk", "手部行走"),
    ("hand walks", "手部行走"),
    ("inch worm", "毛毛虫爬"),
    ("inchworm", "毛毛虫爬"),
    ("renegade row", "Renegade 划船"),

    # 用户走查 round 2 — 补的高频 phrase
    ("against wall", "靠墙"),
    ("against the wall", "靠墙"),
    ("against an incline", "在斜板上"),
    ("carioca quick step", "Carioca 快步"),
    ("chair squat", "椅式深蹲"),
    ("chair leg extended stretch", "坐姿伸腿拉伸"),
    ("chair lower back stretch", "坐姿下背拉伸"),
    ("chair upper body stretch", "坐姿上身拉伸"),
    ("chain press", "铁链推举"),
    ("chain handle extension", "链柄伸展"),
    ("catch and overhead throw", "接住与过头抛"),
    ("calf-machine shoulder shrug", "小腿机耸肩"),
    ("child's pose", "孩童式"),
    ("chin to chest stretch", "下巴贴胸拉伸"),
    ("chest push", "胸推"),
    ("3 point stance", "三点支撑"),
    ("flutter kicks", "蹬腿"),
    ("freehand jump squat", "徒手跳跃深蹲"),
    ("front cone hops", "前向锥跳"),
    ("box jump", "跳箱"),
    ("box squat", "箱式深蹲"),
    ("good morning off pins", "架上早安式"),
    ("hands behind head", "双手抱头"),
    ("hands above head", "双手举过头"),
    ("hands together", "双手合拢"),
    ("hyperextensions", "山羊挺身"),
    ("hyperextension", "山羊挺身"),
    ("reverse hyperextension", "反向挺身"),
    ("knee tuck jumps", "屈膝跳"),
    ("kneeling cable lift", "跪姿绳索抬起"),
    ("kneeling cable twist", "跪姿绳索旋转"),
    ("kneeling forearm stretch", "跪姿前臂拉伸"),
    ("kneeling hip flexor stretch", "跪姿髋屈肌拉伸"),
    ("kneeling jump squat", "跪姿跳跃深蹲"),
    ("looking at ceiling", "仰望天花板"),
    ("lower back stretch", "下背拉伸"),
    ("lying glute stretch", "卧姿臀部拉伸"),
    ("lying machine squat", "卧姿器械深蹲"),
    ("middle back shrug", "中背耸肩"),
    ("middle back stretch", "中背拉伸"),
    ("oblique crunches", "腹斜肌卷腹"),
    ("on your back quad stretch", "仰卧股四头拉伸"),
    ("plank knee to elbow", "平板支撑膝触肘"),
    ("plate pinch", "杠铃片夹"),
    ("plate twist", "杠铃片旋转"),
    ("pin press", "架上推举"),
    ("pin squat", "架上深蹲"),
    ("posterior tibialis", "胫骨后肌"),
    ("press sit-up", "推举仰卧起坐"),
    ("push press", "借力推举"),
    ("rear leg raises", "后抬腿"),
    ("recline pull-ups", "斜身引体向上"),
    ("reverse band", "反弹力带"),
    ("reverse grip", "反握"),
    ("reverse machine flyes", "反向器械飞鸟"),
    ("rocking standing calf raise", "摇摆站姿提踵"),
    ("rope climb", "爬绳"),
    ("rope crunch", "绳索卷腹"),
    ("rope jumping", "跳绳"),
    ("running, treadmill", "跑步, 跑步机"),
    ("seated band hamstring", "坐姿弹力带腿后腱"),
    ("seated calf stretch", "坐姿小腿拉伸"),
    ("shotgun row", "霰弹枪划船"),
    ("side hop-sprint", "侧跳冲刺"),
    ("side jackknife", "侧抬腿"),
    ("side neck stretch", "侧颈拉伸"),
    ("side standing long jump", "侧立定跳远"),
    ("single leg butt kick", "单腿后踢"),
    ("single leg glute", "单腿臀"),
    ("single leg high knee", "单腿高抬腿"),
    ("single leg push off", "单腿推蹬"),
    ("standing biceps cable curl", "站姿绳索二头弯举"),
    ("standing cable lift", "站姿绳索抬起"),
    ("standing cable wood chop", "站姿绳索砍木"),
    ("standing concentration curl", "站姿集中弯举"),
    ("standing gastrocnemius calf stretch", "站姿腓肠肌拉伸"),
    ("standing hip circles", "站姿髋部环绕"),
    ("standing inner-biceps curl", "站姿内二头弯举"),
    ("standing leg curl", "站姿腿弯举"),
    ("standing one-arm cable curl", "站姿单臂绳索弯举"),
    ("standing pelvic tilt", "站姿骨盆倾斜"),
    ("standing rope crunch", "站姿绳索卷腹"),
    ("standing soleus calf stretch", "站姿比目鱼肌拉伸"),
    ("standing toe touches", "站姿触脚趾"),
    ("tire flip", "翻轮胎"),
    ("toe touch", "触脚趾"),
    ("upper back stretch", "上背拉伸"),
    ("upright cable row", "直立绳索划船"),
    ("walking high knees", "行走高抬腿"),
    ("walking high kicks", "行走高踢"),
    ("wall ball", "靠墙球"),
    ("wall press hip flexor stretch", "靠墙髋屈肌拉伸"),
    ("wall slides", "靠墙滑行"),
    ("wood chop", "砍木"),
    ("wrist roller", "腕轮"),
    ("zercher carry", "Zercher 搬运"),

    # 复合动作 (高频)
    ("romanian deadlift", "罗马尼亚硬拉"),
    ("sumo deadlift", "相扑硬拉"),
    ("stiff leg deadlift", "直腿硬拉"),
    ("stiff-legged deadlift", "直腿硬拉"),
    ("deficit deadlift", "赤字硬拉"),
    ("rack pull", "架上拉"),
    ("good morning", "早安式"),

    ("hack squat", "哈克深蹲"),
    ("front squat", "前蹲"),
    ("back squat", "后蹲"),
    ("goblet squat", "高脚杯深蹲"),
    ("zercher squat", "Zercher 深蹲"),
    ("split squat", "分腿蹲"),
    ("bulgarian split squat", "保加利亚分腿蹲"),
    ("box squat", "箱式深蹲"),
    ("jump squat", "跳跃深蹲"),
    ("sissy squat", "Sissy 深蹲"),
    ("pistol squat", "手枪式深蹲"),
    ("wall squat", "靠墙静蹲"),

    ("bench press", "卧推"),
    ("close-grip bench press", "窄距卧推"),
    ("incline bench press", "上斜卧推"),
    ("decline bench press", "下斜卧推"),
    ("floor press", "地板推举"),
    ("board press", "板上卧推"),
    ("pin press", "架上推举"),
    ("push press", "借力推举"),
    ("overhead press", "过头推举"),
    ("shoulder press", "肩推"),
    ("military press", "军推"),
    ("arnold press", "阿诺德推举"),
    ("french press", "颈后臂屈伸"),

    ("lat pulldown", "高位下拉"),
    ("pulldown", "下拉"),
    ("pushdown", "下压"),
    ("triceps pushdown", "三头下压"),
    ("face pull", "面拉"),
    ("upright row", "直立划船"),
    ("bent over row", "俯身划船"),
    ("bent-over row", "俯身划船"),
    ("t-bar row", "T 杠划船"),
    ("seal row", "海豹划船"),
    ("inverted row", "反向划船"),

    ("bicep curl", "二头弯举"),
    ("biceps curl", "二头弯举"),
    ("hammer curl", "锤式弯举"),
    ("preacher curl", "牧师椅弯举"),
    ("concentration curl", "集中弯举"),
    ("zottman curl", "Zottman 弯举"),
    ("spider curl", "蜘蛛弯举"),
    ("reverse curl", "反向弯举"),
    ("drag curl", "拖拉弯举"),
    ("wrist curl", "腕弯举"),
    ("21s", "21 响弯举"),
    ("incline curl", "上斜弯举"),

    ("tricep extension", "三头伸展"),
    ("triceps extension", "三头伸展"),
    ("skull crusher", "颅骨碎裂者"),
    ("skullcrusher", "颅骨碎裂者"),
    ("kickback", "后踢"),
    ("triceps kickback", "三头后踢"),

    ("lateral raise", "侧平举"),
    ("front raise", "前平举"),
    ("rear delt raise", "后束侧平举"),
    ("rear delt fly", "后束飞鸟"),
    ("reverse fly", "反向飞鸟"),
    ("calf raise", "提踵"),

    ("leg press", "腿举"),
    ("leg extension", "腿屈伸"),
    ("leg curl", "腿弯举"),
    ("leg raise", "抬腿"),
    ("hanging leg raise", "悬挂抬腿"),
    ("knee raise", "提膝"),
    ("leg lift", "举腿"),
    ("flutter kick", "蹬腿"),
    ("scissor kick", "剪刀腿"),

    ("walking lunge", "行走弓步"),
    ("reverse lunge", "反向弓步"),
    ("side lunge", "侧弓步"),
    ("lateral lunge", "侧弓步"),
    ("step-up", "登阶"),
    ("step up", "登阶"),

    ("hip thrust", "髋推"),
    ("glute bridge", "臀桥"),
    ("hip bridge", "髋桥"),
    ("kettlebell swing", "壶铃摇摆"),
    ("turkish get-up", "土耳其起立"),
    ("farmers walk", "农夫行走"),
    ("farmer's walk", "农夫行走"),
    ("yoke walk", "Yoke 行走"),
    ("sled push", "雪橇推"),
    ("sled drag", "雪橇拖拉"),
    ("battle rope", "战绳"),
    ("box jump", "跳箱"),
    ("medicine ball", "药球"),
    ("atlas stone", "阿特拉斯石"),
    ("clean and jerk", "挺举"),
    ("clean and press", "翻举推举"),
    ("hang clean", "悬垂翻举"),
    ("power clean", "高翻"),
    ("snatch", "抓举"),
    ("hang snatch", "悬垂抓举"),
    ("power snatch", "力量抓举"),

    ("sit-up", "仰卧起坐"),
    ("crunch", "卷腹"),
    ("reverse crunch", "反向卷腹"),
    ("bicycle crunch", "自行车卷腹"),
    ("v-up", "V 字起"),
    ("toe touch", "触脚趾"),
    ("russian twist", "俄罗斯转体"),
    ("mountain climber", "登山者"),
    ("hollow hold", "Hollow 保持"),
    ("dead bug", "死虫"),
    ("bird dog", "鸟狗"),

    ("face the wall", "面壁"),
    ("wall sit", "靠墙静坐"),
    ("wall slide", "靠墙滑行"),
    ("wall ball", "靠墙球"),

    ("good girl", "美腿机内收"),
    ("bad girl", "美腿机外展"),
    ("hip adduction", "髋内收"),
    ("hip abduction", "髋外展"),

    ("pec deck", "蝴蝶机"),
    ("pec fly", "胸飞鸟"),
    ("chest fly", "胸飞鸟"),
    ("dumbbell fly", "哑铃飞鸟"),
    ("cable fly", "绳索飞鸟"),
    ("cable crossover", "绳索交叉"),
    ("crossover", "交叉"),

    ("shrug", "耸肩"),
    ("shoulder shrug", "肩部耸肩"),

    ("smith machine", "史密斯机"),
    ("hammer strength", "Hammer Strength"),
    ("ez bar", "EZ 杆"),
    ("ez-bar", "EZ 杆"),
    ("e-z bar", "EZ 杆"),
    ("e-z curl bar", "EZ 弯举杆"),
    ("straight bar", "直杆"),

    ("chin up", "正握引体向上"),
    ("chin-up", "正握引体向上"),
    ("pull up", "引体向上"),
    ("pull-up", "引体向上"),
    ("push up", "俯卧撑"),
    ("push-up", "俯卧撑"),
    ("muscle up", "双力臂"),
    ("muscle-up", "双力臂"),
    ("muscle ups", "双力臂"),
    ("toes to bar", "举腿至杠"),
    ("knees to elbows", "膝触肘"),

    # 拉伸类
    ("stretch", "拉伸"),
    ("smr", "肌筋膜放松"),

    # 有氧
    ("jumping jack", "开合跳"),
    ("high knee", "高抬腿"),
    ("burpees", "波比跳"),
    ("running", "跑步"),
    ("rowing", "划船有氧"),
    ("cycling", "自行车"),
]

# ─── 单词级翻译 (上一层没命中, 单词替换) ───
WORD_ZH = {
    # 设备
    "barbell": "杠铃",
    "dumbbell": "哑铃",
    "dumbbells": "哑铃",
    "kettlebell": "壶铃",
    "kettlebells": "壶铃",
    "cable": "绳索",
    "machine": "器械",
    "smith": "史密斯",
    "band": "弹力带",
    "bands": "弹力带",
    "bodyweight": "自重",
    "freehand": "徒手",
    "weighted": "负重",
    "rope": "绳索",
    "trap-bar": "六角杠",
    "trap": "斜方肌",
    "ball": "球",
    "stability": "瑜伽球",
    "swiss": "瑞士球",
    "medicine": "药球",
    "battle": "战绳",
    "plate": "杠铃片",
    "chains": "铁链",
    "bench": "卧推凳",
    "preacher": "牧师椅",
    "platform": "台阶",
    "box": "箱",
    "bar": "杠",
    "rack": "架",
    "rings": "吊环",
    "ring": "吊环",
    "wheel": "腹肌轮",
    "roller": "腹肌轮",
    "tire": "轮胎",
    "sled": "雪橇",
    "rower": "划船机",
    "treadmill": "跑步机",
    "stationary": "固定",
    "elliptical": "椭圆机",
    "stairmaster": "登山机",
    "bike": "单车",
    "rope-pulley": "绳索滑轮",
    "pulley": "滑轮",
    "lever": "杠杆",
    "tube": "弹力管",
    "tubing": "弹力管",
    "log": "原木杠",
    "atlas": "阿特拉斯",
    "stone": "石",
    "yoke": "Yoke",
    "axle": "粗杆",

    # 动作
    "press": "推举",
    "presses": "推举",
    "curl": "弯举",
    "curls": "弯举",
    "row": "划船",
    "rows": "划船",
    "raise": "举起",
    "raises": "举起",
    "extension": "伸展",
    "extensions": "伸展",
    "fly": "飞鸟",
    "flies": "飞鸟",
    "flyes": "飞鸟",
    "lunge": "弓步",
    "lunges": "弓步",
    "squat": "深蹲",
    "squats": "深蹲",
    "deadlift": "硬拉",
    "deadlifts": "硬拉",
    "swing": "摇摆",
    "swings": "摇摆",
    "twist": "扭转",
    "twists": "扭转",
    "kick": "踢",
    "kicks": "踢",
    "pull": "拉",
    "pulls": "拉",
    "push": "推",
    "pushes": "推",
    "thrust": "推",
    "thrusts": "推",
    "lift": "举",
    "lifts": "举",
    "walk": "行走",
    "walks": "行走",
    "jump": "跳跃",
    "jumps": "跳跃",
    "throw": "抛",
    "throws": "抛",
    "drop": "下落",
    "drops": "下落",
    "carry": "搬运",
    "carries": "搬运",
    "hold": "保持",
    "holds": "保持",
    "drag": "拖拉",
    "drags": "拖拉",
    "rotation": "旋转",
    "rotations": "旋转",
    "circle": "环绕",
    "circles": "环绕",
    "drill": "训练",
    "drills": "训练",
    "warmup": "热身",
    "warm-up": "热身",
    "stretch": "拉伸",
    "stretches": "拉伸",
    "stretching": "拉伸",
    "complex": "组合",
    "snatch": "抓举",
    "clean": "翻举",
    "jerk": "挺举",
    "shrug": "耸肩",
    "shrugs": "耸肩",
    "crunch": "卷腹",
    "crunches": "卷腹",
    "plank": "平板支撑",
    "planks": "平板支撑",
    "bridge": "桥式",
    "bridges": "桥式",
    "hold": "保持",
    "balance": "平衡",
    "abduction": "外展",
    "adduction": "内收",
    "flexion": "屈曲",
    "rotation": "旋转",
    "isometric": "静态",

    # 肌群
    "bicep": "二头",
    "biceps": "二头",
    "tricep": "三头",
    "triceps": "三头",
    "chest": "胸",
    "pec": "胸",
    "pecs": "胸肌",
    "shoulder": "肩",
    "shoulders": "肩",
    "back": "背",
    "leg": "腿",
    "legs": "腿",
    "quad": "股四头",
    "quads": "股四头",
    "hamstring": "腿后腱",
    "hamstrings": "腿后腱",
    "glute": "臀",
    "glutes": "臀",
    "calf": "小腿",
    "calves": "小腿",
    "lat": "背阔肌",
    "lats": "背阔肌",
    "ab": "腹",
    "abs": "腹肌",
    "abdominal": "腹",
    "abdominals": "腹肌",
    "core": "核心",
    "forearm": "前臂",
    "forearms": "前臂",
    "delt": "三角肌",
    "delts": "三角肌",
    "deltoid": "三角肌",
    "neck": "颈",
    "obliques": "腹斜肌",
    "oblique": "腹斜肌",
    "hip": "髋",
    "hips": "髋",
    "knee": "膝",
    "knees": "膝",
    "ankle": "踝",
    "wrist": "腕",
    "wrists": "腕",
    "elbow": "肘",
    "lower-back": "下背",
    "upper-back": "上背",

    # 位置 / 修饰
    "standing": "站姿",
    "seated": "坐姿",
    "sitting": "坐姿",
    "lying": "卧姿",
    "kneeling": "跪姿",
    "supine": "仰卧",
    "prone": "俯卧",
    "incline": "上斜",
    "decline": "下斜",
    "flat": "平板",
    "bent-over": "俯身",
    "bent": "弯曲",
    "bent-knee": "屈膝",
    "single-leg": "单腿",
    "single-arm": "单臂",
    "one-leg": "单腿",
    "one-arm": "单臂",
    "two-arm": "双臂",
    "one": "单",
    "two": "双",
    "alternating": "交替",
    "alternate": "交替",
    "reverse": "反向",
    "front": "前",
    "side": "侧",
    "rear": "后束",
    "lateral": "侧",
    "overhead": "过头",
    "close-grip": "窄距",
    "wide-grip": "宽距",
    "close": "窄",
    "wide": "宽",
    "narrow": "窄",
    "neutral-grip": "中立握",
    "neutral": "中立",
    "hammer-grip": "锤式握",
    "underhand": "反握",
    "overhand": "正握",
    "cross-body": "对侧",
    "cross": "交叉",
    "high": "高位",
    "low": "低位",
    "mid": "中位",
    "deep": "深",
    "wall": "靠墙",
    "floor": "地面",
    "ground": "地面",
    "forward": "向前",
    "backward": "向后",
    "back-and-forth": "前后",
    "outside": "外侧",
    "inside": "内侧",
    "inner": "内侧",
    "outer": "外侧",
    "upper": "上",
    "lower": "下",
    "vertical": "垂直",
    "horizontal": "水平",
    "elevated": "抬高",
    "elevation": "抬高",
    "weighted": "负重",
    "loaded": "负重",
    "straight": "直",
    "straight-leg": "直腿",
    "straight-arm": "直臂",
    "stiff-leg": "直腿",
    "stiff-legged": "直腿",
    "bent-leg": "屈腿",
    "bent-arm": "屈臂",

    # 握/姿
    "grip": "握法",
    "stance": "站位",
    "wide-stance": "宽站位",
    "narrow-stance": "窄站位",
    "sumo": "相扑式",

    # 时间/节奏
    "speed": "速度",
    "slow": "慢速",
    "fast": "快速",
    "tempo": "节奏",
    "explosive": "爆发",
    "pause": "暂停",
    "static": "静态",
    "dynamic": "动态",

    # 类别词
    "exercise": "动作",
    "training": "训练",
    "drill": "训练",

    # 额外覆盖 (高频未识别词)
    "adductor": "内收肌",
    "abductor": "外展肌",
    "groin": "腹股沟",
    "heel": "脚跟",
    "heels": "脚跟",
    "touch": "触碰",
    "touches": "触碰",
    "touchers": "触碰",
    "toucher": "触碰",
    "tap": "点触",
    "taps": "点触",
    "diagonal": "对角",
    "bound": "跳跃",
    "anterior": "前侧",
    "posterior": "后侧",
    "tibialis": "胫前肌",
    "trainer": "训练",
    "crawl": "爬行",
    "crawls": "爬行",
    "bend": "侧弯",
    "bends": "侧弯",
    "sprint": "冲刺",
    "sprints": "冲刺",
    "rollout": "滚轮推",
    "rollouts": "滚轮推",
    "apart": "分开",
    "behind": "后",
    "around": "环绕",
    "foot": "脚",
    "feet": "脚",
    "gravity": "重力",
    "world": "世界",
    "worlds": "世界",
    "air": "空气",
    "windmill": "风车",
    "windmills": "风车",
    "renegade": "Renegade",
    "roller": "滚轮",
    "rollers": "滚轮",
    "stones": "石",
    "arm": "手臂",
    "arms": "手臂",
    "hand": "手",
    "hands": "手",
    "arnold": "阿诺德",
    "bicycling": "骑车",
    "bicycle": "自行车",
    "body": "身体",
    "butt": "臀",
    "butterfly": "蝶式",
    "multiple": "多",
    "response": "反应",
    "skip": "跳",
    "skips": "跳",
    "brachialis": "肱肌",
    "bradford": "Bradford",
    "hang": "悬垂",
    "position": "姿势",
    "assisted": "辅助",
    "adductions": "内收",
    "abductions": "外展",
    "raises": "举起",  # 已在 word map 但补 plural 防漏
    "circles": "环绕",  # 已存在但补 explicit
    "circle": "环绕",
    "bird": "鸟",
    "dog": "狗",
    "rocky": "Rocky",
    "trap-bar": "六角杠",
    "guillotine": "Guillotine",
    "barbell-row": "杠铃划船",
    "deficit": "赤字",
    "deficits": "赤字",
    "ja": "JA",
    "jm": "JM",
    "leverage": "杠杆",
    "single": "单",
    "double": "双",
    "triple": "三",
    "raised": "抬高",
    "elevated": "抬高",  # 已有但补
    "incline": "上斜",  # 已有
    "flat-bench": "平凳",
    "flat-bar": "直杆",
    "lock": "锁定",
    "locks": "锁定",
    "anchor": "锚",
    "anchored": "锚定",
    "tucks": "屈膝",  # 已有
    "raise-up": "起身",
    "windshield-wipers": "雨刷",
    "scissor-kicks": "剪刀腿",
    "scissor": "剪刀",
    "kickboxing": "踢拳",
    "rope-pull": "绳拉",
    "rope-climb": "爬绳",
    "climb": "攀爬",
    "climbs": "攀爬",
    "row-twist": "划船扭转",
    "isolation": "孤立",
    "compound": "复合",
    "auxiliary": "辅助",
    "main": "主",
    "warming-up": "热身",
    "warmup": "热身",
    "warm-up": "热身",
    "cool-down": "放松",
    "side-bend": "侧弯",
    "side-bends": "侧弯",
    "side-leg": "侧腿",
    "leg-curls": "腿弯举",  # 已有 phrase, 保险
    "fingers": "手指",
    "finger": "手指",
    "thumb": "拇指",
    "thumbs": "拇指",
    "grip-strength": "握力",
    "strength": "力量",
    "endurance": "耐力",
    "speed-skater": "速滑步",
    "speed-skaters": "速滑步",
    "ice": "冰",
    "ground": "地面",  # 已有
    "ceiling": "天花板",
    "overhead-walk": "过头行走",
    "front-rack": "前架",
    "back-rack": "后架",
    "zercher": "Zercher",
    "kang": "Kang",
    "pendlay-row": "Pendlay 划船",
    "rdl": "罗马尼亚硬拉",
    "rdls": "罗马尼亚硬拉",
    "press-down": "下压",
    "press-up": "推起",
    "press-out": "推出",
    "pin-press": "架上推举",
    "pins": "插销",
    "pin": "插销",
    "pin-squat": "架上深蹲",
    "high-pull": "高位拉",
    "high-pulls": "高位拉",
    "x-band": "X 弹力带",
    "x-bands": "X 弹力带",
    "pec-deck": "蝴蝶机",
    "rope-pulldown": "绳索下拉",
    "stretch-band": "弹力带拉伸",
    "stretching-band": "弹力带拉伸",
    "abduction-machine": "外展机",
    "adduction-machine": "内收机",
    "abductor-machine": "外展机",
    "adductor-machine": "内收机",
    "weighted-back": "负重后",
    "thigh": "大腿",
    "thighs": "大腿",
    "shin": "胫",
    "shins": "胫",
    "buttocks": "臀部",
    "groin": "腹股沟",  # 已有
    "pubic": "耻骨",
    "muscle": "肌肉",
    "muscles": "肌肉",
    "stretch-rope": "拉伸绳",
    "ups": "向上",  # 复数 "pull ups" 中 ups 已经被 phrase 命中, 这是兜底
    "ins": "向内",
    "outs": "向外",
    "downs": "向下",
    "ab": "腹",
    "ez": "EZ",
    "imto": "至",
    "guillotine": "Guillotine",
    "powerlifting": "力量举",
    "olympic": "奥林匹克",
    "step": "登阶",
    "steps": "登阶",
    "jack": "跳",
    "jacks": "跳",
    "running": "跑步",
    "runner": "跑步者",
    "runners": "跑步者",
    "row": "划船",  # 已存在重复无害
    "tuck": "屈膝",
    "tucks": "屈膝",
    "good-girl": "美腿机内收",
    "bad-girl": "美腿机外展",
    "pump": "泵",
    "pumps": "泵",
    "kneeling": "跪姿",
    "spider": "蜘蛛",
    "spiders": "蜘蛛",
    "spiderman": "蜘蛛侠",
    "dragon": "龙",
    "dragons": "龙",
    "scorpion": "蝎子",
    "frog": "青蛙",
    "monkey": "猿",
    "donkey": "驴",
    "duck": "鸭",
    "fire": "火",
    "wiper": "雨刷",
    "wipers": "雨刷",
    "windshield": "风挡",
    "splits": "劈叉",
    "split": "分腿",
    "bow": "鞠躬",
    "skate": "滑步",
    "skater": "滑步",
    "skaters": "滑步",
    "all-fours": "四点支撑",
    "all": "全",
    "fours": "四点",
    "see-saw": "翘翘板",
    "see": "看",
    "saw": "锯",
    "behind-the-back": "背后",
    "behind-the-neck": "颈后",
    "around-the-world": "环绕",
    "snow": "雪",
    "angel": "天使",
    "angels": "天使",
    "powell": "Powell",
    "iron": "铁",
    "cross": "交叉",
    "crucifix": "Crucifix",
    "pendlay": "Pendlay",
    "yates": "Yates",
    "kroc": "Kroc",
    "meadows": "Meadows",
    "tate": "Tate",
    "ja": "Ja",
    "jm": "JM",
    "saxon": "Saxon",
    "javelin": "标枪",
    "shovel": "铁锹",
    "punch": "出拳",
    "punches": "出拳",
    "uppercut": "上勾拳",
    "hook": "勾拳",
    "hooks": "勾拳",
    "jab": "刺拳",
    "kicks": "踢",
    "kicking": "踢",
    "circuit": "循环",
    "tabata": "塔巴塔",
    "interval": "间歇",
    "rest": "休息",
    "warm": "热身",
    "cooldown": "放松",
    "cool-down": "放松",
    "active": "主动",
    "passive": "被动",
    "release": "放松",
    "rolling": "滚动",
    "roll": "滚动",
    "rolls": "滚动",
    "drop-set": "递减组",
    "isometric": "静态",
    "concentric": "向心",
    "eccentric": "离心",
    "pulse": "脉动",
    "pulses": "脉动",
    "good": "好",
    "girl": "(女)",
    "bad": "差",
    "boy": "(男)",
    "bear": "熊",
    "monster": "怪兽",
    "demon": "恶魔",
    "boxing": "拳击",
    "kickboxing": "踢拳",
    "muay": "泰拳",
    "thai": "泰式",
    "wrestler": "摔跤",
    "wrestlers": "摔跤",
    "wrestle": "摔跤",
    "wrestling": "摔跤",
    "burpee": "波比",
    "burpees": "波比",
    "thruster": "推举蹲",
    "thrusters": "推举蹲",
    "windmill": "风车",
    "halo": "光环绕头",
    "halos": "光环绕头",
    "carry": "搬运",
    "carries": "搬运",
    "russian": "俄罗斯",
    "v-sit": "V字坐",
    "v-up": "V字起",
    "v-ups": "V字起",
    "scissors": "剪刀",
    "kneeling": "跪姿",
    "kneeling-down": "跪下",
    "froggers": "蛙跳",
    "frogger": "蛙跳",
    "frog-pumps": "蛙跳泵",
    "side-bend": "侧弯",
    "side-bends": "侧弯",
    "high-knees": "高抬腿",
    "knees-high": "高抬腿",
    "wide-stance": "宽站位",
    "rdl": "罗马尼亚硬拉",
    "sldl": "直腿硬拉",
    "abductor": "外展肌",
    "lockout": "锁定",
    "lockouts": "锁定",
    "negatives": "负向",
    "negative": "负向",
    "partial": "部分",
    "partials": "部分",
    "half": "半",
    "quarter": "四分之一",
    "third": "三分之一",
    "full": "全",
    "complete": "完整",
    "extended": "延伸",
    "extended-range": "扩展行程",
    "controlled": "受控",
    "tempo": "节奏",
    "slow-mo": "慢动作",
    "tempos": "节奏",
    "drops": "递减",
    "rest-pause": "休息暂停",
    "21": "21",
    "drag": "拖",
    "drags": "拖",
    "snatch-grip": "抓举握",
    "clean-grip": "翻举握",
    "trap-3": "斜方肌 3",
    "rotator": "肩袖",
    "cuff": "肩袖",
    "torso": "躯干",
    "spine": "脊柱",
    "thoracic": "胸椎",
    "lumbar": "腰椎",
    "scapula": "肩胛",
    "shoulder-pack": "肩胛收缩",
    "long-cycle": "长循环",
    "advanced": "进阶",
    "beginner": "初学者",
    "intermediate": "中级",
    "open": "张开",
    "open-palm": "张掌",
    "palm": "掌",
    "palms": "掌",
    "closed": "闭合",
    "behind-head": "头后",
    "behind-the-head": "头后",
    "neck": "颈",
    "hip-shift": "髋移动",
    "shift": "移动",
    "shifts": "移动",
    "knee-tuck": "屈膝收腿",
    "knee-up": "提膝",
    "knee-ups": "提膝",
    "pull-through": "穿拉",
    "pull-throughs": "穿拉",
    "pass-through": "穿过",
    "pass": "穿过",
    "throughout": "贯穿",
    "explosive": "爆发",
    "powerful": "有力",
    "iron-cross": "Iron Cross",
    "diamond": "钻石",
    "wide-pushup": "宽距俯卧撑",
    "decline-pushup": "下斜俯卧撑",
    "incline-pushup": "上斜俯卧撑",
    "ski": "滑雪",
    "skier": "滑雪",
    "skiers": "滑雪",
    "wall-walk": "靠墙倒立行走",
    "wall-walks": "靠墙倒立行走",
    "handstand": "倒立",
    "handstands": "倒立",
    "press-up": "起身",
    "head": "头",
    "headstand": "头倒立",
    "extension-pulse": "伸展脉动",

    # 名字结构词
    "with": "配",
    "and": "与",
    "on": "在",
    "to": "至",
    "for": "用于",
    "the": "",
    "a": "",
    "an": "",
    "as": "作为",
    "from": "从",
    "in": "在",
    "over": "过",
    "up": "向上",
    "down": "向下",
    "out": "向外",
    "off": "离",
    "across": "横跨",
    "around": "环绕",
    "through": "贯通",
}

# ─── 一些固定词汇 (人名/品牌, 保留英文) ───
KEEP_AS_IS = {
    "T", "Z", "V", "I", "Y", "L", "X",
    "SMR", "21s",
    "Arnold", "Atlas", "Zercher", "Zottman",
    "Bulgarian", "Cuban", "Russian", "Romanian",
    "Sissy",
    "Yoke", "Stairmaster",
    "Crucifix", "Spiderman",
    "Sled", "Pistol", "Goblet",
    "Iron Cross",
    "Olympic", "Inchworm",
    "Hercules",
}


def translate(name: str) -> str:
    """对一个英文动作名生成中文翻译."""
    lower = name.lower().strip()

    # 1) 整名精确命中
    if lower in EXACT_ZH:
        return EXACT_ZH[lower]

    # 2) 短语级 word-boundary 替换 — 长 phrase 先
    # 用 \b regex 防止 "crunch" 误匹配 "crunches" 子串 (留下 "es")
    sorted_phrases = sorted(PHRASE_ZH, key=lambda p: -len(p[0]))
    work = lower
    placeholders = []
    for en_phrase, zh in sorted_phrases:
        pattern = re.compile(r'\b' + re.escape(en_phrase) + r'\b')
        if pattern.search(work):
            ph = f"\x00{len(placeholders)}\x00"
            placeholders.append(zh)
            work = pattern.sub(ph, work)

    # 3) 单词级替换 (剩余英文单词)
    # 先按非字母字符 split 保留分隔
    tokens = re.split(r'([^a-zA-Z0-9\x00-]+)', work)
    out_tokens = []
    for tok in tokens:
        if not tok:
            continue
        # 占位符直接保留
        if '\x00' in tok:
            out_tokens.append(tok)
            continue
        low = tok.lower()
        if low in WORD_ZH:
            zh = WORD_ZH[low]
            if zh:  # 空 = 跳过 (the/a/an)
                out_tokens.append(zh)
        elif tok in KEEP_AS_IS or tok.isupper() or low.startswith('z') and len(low) <= 2:
            # 保留品牌/姓氏/单字母
            out_tokens.append(tok.capitalize() if not tok.isupper() else tok)
        elif tok in '-/(),':
            out_tokens.append(tok)
        else:
            # 未识别 — 保留首字母大写英文 (用户后续可补)
            out_tokens.append(tok.capitalize())

    # 4) 还原占位符
    result = ''.join(out_tokens)
    for i, zh in enumerate(placeholders):
        result = result.replace(f'\x00{i}\x00', zh)

    # 5) 清理空格/连字符 (中文不需要英文风格的空格)
    result = re.sub(r'\s+', '', result)
    result = re.sub(r'^-+|-+$', '', result)
    result = re.sub(r'-+', ' - ', result)  # 保留中间 hyphen 当分隔符
    result = result.strip()

    # 如果完全没翻译, 返回原 English
    if not result or all(c.isalpha() and ord(c) < 256 for c in result):
        return name
    return result


def confidence(name: str, zh: str) -> float:
    """翻译可信度 — 0-1. 数值越大越可信.
    定义: zh 中非英文字符比例 (中文 + 标点). 全中文 = 1.0, 全英文 = 0.
    """
    if not zh:
        return 0
    en_chars = sum(1 for c in zh if c.isascii() and c.isalpha())
    return 1 - en_chars / len(zh)


def main():
    with open(JSON_PATH, encoding='utf-8') as f:
        data = json.load(f)

    names = sorted(set(e['name'] for e in data))
    print(f"Total unique names: {len(names)}")

    out_path = os.path.join(REPO_ROOT, 'Maso/Resources/zh-Hans.lproj/ExerciseNames.strings')
    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    THRESHOLD = 0.4  # 翻译至少 40% 中文字符才写入 — 低于此 fallback raw 英文.
    # 注: 0.4 是经验值, 像 "Renegade 划船" (4 字英文 + 2 字中文) conf≈0.33 就 skip;
    # 而 "Bradford / Rocky 推举" 类的"人名 + 中文动作" 命中 0.5 写入, 这样 chip 上
    # 至少有中文主词, 人名作为修饰 OK.
    written = 0
    skipped = []
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('/* Auto-generated exercise names — zh-Hans.\n')
        f.write('   Source: scripts/translate_exercise_names.py + WORD/PHRASE maps.\n')
        f.write('   Only entries with >60%% Chinese chars are written; rest fallback to English. */\n\n')
        for n in names:
            zh = translate(n)
            conf = confidence(n, zh)
            if conf < THRESHOLD:
                skipped.append((n, zh, conf))
                continue
            zh_safe = zh.replace('"', '\\"')
            n_safe = n.replace('"', '\\"')
            f.write(f'"{n_safe}" = "{zh_safe}";\n')
            written += 1

    print(f"Written: {written}/{len(names)} entries to {out_path}")
    print(f"Skipped (low confidence, will fallback to English): {len(skipped)}")
    print("\nSample of skipped entries (for manual review later):")
    for n, zh, conf in skipped[:20]:
        print(f"  [conf {conf:.2f}]  {n}  →  {zh}")
    if len(skipped) > 20:
        print(f"  ... and {len(skipped) - 20} more")


if __name__ == '__main__':
    main()
